### ISSUE TITLE
Amount control in documents

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1013]
Надо постаивить контроль что 
TaxList.Total("Amount") = ItemList.Total("TaxAmount")
SpecialOffers.Total("Amount") = ItemList.Total("OffersAmount")

**Comment by andreyvorobyov2** [comment]
Нельзя этого делать, потому что не смогут вручную подгонять копейки в налогах,
если меняют сумму налога вручную то меняется значение в колонке ManualAmount.
TaxList.Total("ManualAmount") = ItemList.Total("TaxAmount")
ManualAmount всегда равен TaxAmount.
а вот это вот TaxList.Total("Amount") это то как посчитала программа.
