### ISSUE TITLE
Stock adjustment as surplus/ Stock adjustment as write off movements by registers R5021 Revenues/R5022 Expenses

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1014]
Для документа Stock adjustment as surplus необходимо добавить движения по регистру R5021 Revenues
Для документа Stock adjustment as write off необходимо добавить движения по регистру R5022 Expenses

**Comment by andreyvorobyov2** [comment]
нужно в складские документы добавлять валюты, сумма оприходования есть а вот в какой она валюте непонятно. 100 денег нельзя кинуть в регистр доходов.
а еще она противоречит задачи партионного учета, в момент списания стоимость неизвестна, сколько кидать в регистр расходов непонятно.
у оприходуемых товаров еще есть и НДС которую тоже нужно учесть, вообщем тут отдельным документом как то надо
если все это сделать в складском документе получется тот же PI и SI только без контрагентов.
