### ISSUE TITLE
BUG? check the operation of Quantity Compare plugin 

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#102]
Вопрос в вот такой форме:
![image](https://user-images.githubusercontent.com/11927866/87251002-78eb3e80-c41d-11ea-9b7e-f135662c633f.png)
И там есть вот такая не подписанная кнопка, не понятно что она делает:
![image](https://user-images.githubusercontent.com/11927866/87251016-90c2c280-c41d-11ea-8beb-7c6df69f76dc.png)
И не понятно что должнол быть в результате.
Тест 
_010020 check the operation of Quantity Compare plugin (comparison of the plan / fact in Goods reciept) 
ожидает, что там будет перенос из одного поля в другое, но не понятна логика. Напомните плиз.

**Comment by Severnity** [comment]
Форма используется при приемке товара.
Вначале кладовщик сканирует товар вот в этой форме
![изображение](https://user-images.githubusercontent.com/66120736/87251183-651df780-c472-11ea-9050-079f1be37ed7.png). Данные по отсканированному товару должны были сохраняться в регистр, так чтобы можно было посмотреть кто что отсканировал, а также не потерялись данные если программа во время сканировки вылетит. 
После того как весь товар отсканирован кладовщик переключается в режим сравнения (с помощью кнопки) и анализирует разницы либо может сразу заполнить остканированным количеством документ.
![изображение](https://user-images.githubusercontent.com/66120736/87251222-ac0bed00-c472-11ea-9501-91a58c6f2ae3.png)
Сама форма до конца не доделана, поэтому тест будет падать. Задача по форме https://github.com/IRPTeam/IRP/issues/11
