### ISSUE TITLE
Search in list form with store from ItemList

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1031]
При поиске любого значение выскакивает ошибка

![image](https://user-images.githubusercontent.com/32883592/127913969-b8fff251-de39-46ec-a8ba-4d990ba2effc.png)

**Comment by DitriXNew** [comment]
@seramiti это можно как то покрывать тестами?

**Comment by Severnity** [comment]
попробовать можно. @bryaleks а что это за форма?

**Comment by bryaleks** [comment]
@Severnity на скрине PI, язак интерфейса tr, язык данных en
