### ISSUE TITLE
Total amount when BR Basis OnChange

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1051]
В поступлении денежных средст добавляю строку, выбираю партнера выбираю его документ (соглашение по докуентам)
Не отрабатывает пересчет сумма внизу справа, хотя подставил сумму в строку
Копирую строку - пересчет отрабатывает, выбираю док не отрабатывает
Провожу док - отрабатывает

**Comment by andreyvorobyov2** [comment]
исправлено для документов:
Bank payment
Bank receipt
Cash payment
Cash receipt
