### ISSUE TITLE
Amount with VAT in PL

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1062]
в R5022T_Expenses и в R5021T_Revenues ресурсы надо сделать Amount и AmountWithTaxes для тех, кто считает рентабельность включая налоги.

**Comment by andreyvorobyov2** [comment]
R5021T_Revenues
-- Sales invoice
-- Retail sales receipt
-- Retail return receipt
-- Cash revenue
-- Sales return

R5022T_Expenses
--Purchase return
--Cash expense
--Purchase invoice
