### ISSUE TITLE
RezervationDate in ItemList

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1069]
Нужно перенести дату резерва товаров в SO в строки.
Для того что бы более точно понимать когда был зарезервирован товар
Реквизит доступен для редактирования только при соответствующем ProcurementMethod

**Comment by bryaleks** [comment]
![image](https://user-images.githubusercontent.com/32883592/131738830-c9b2f15e-7ade-4528-8290-a3d44b41c38e.png)

Вот это разве не нужно убрать? @andreyvorobyov2

**Comment by andreyvorobyov2** [comment]
убрал
