### ISSUE TITLE
UniqueID in not unique at PostgreSQL

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#107]
После перехода на postgre sql процедура CheckUniqueIDBeforeWrite в модуле UniqueID перестала отрабатывать. Уникальность на постргре идет слева а не справа. Так как длинна поля UniqueID позволяет, решили убрав справа 12.

//Source.UniqueID = "_" + Right(String(New UUID()), 12);
Source.UniqueID = "_" + StrReplace(String(New UUID()),"-","");

**Comment by DitriXNew** [comment]
только не так:
