### ISSUE TITLE
Bugs in Compare Quantity data proccessor

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#11]
При работе в форме сравнения Compare Quantity (находится в документе Goods receipt) возникают следующие баги:
1. При добавлении товара в форму сравнения вручную необходимо заполнять единицу измерения из item key
2. При добавлении товара вручную на вкладке "PhysItemList" новое количество не отображается на вкладке "CompareItemList"
3. При переносе данных в Goods receipt из формы сравнения не переносится количество по товару заполненному на вкладке "CompareItemList" (нет синхронизации с "PhysItemList")
4. В случае если при создании Goods receipt было заполнено поле Sales order и Currency, то при переносе данных из формы сравнения они очищаться не должны.
Поле Sales order заполняется в том случае, если изначально пользователь создал Sales order на товар под закупку у поставщика, потом на его основании создал Purchase order/Purchase invoice и Goods receipt.
Поле Currency заполняется для того, чтобы избежать ситуации когда в одном Goods receipt будут документы-основания с разными валютами.
![image](https://user-images.githubusercontent.com/66120736/83725914-670ec280-a64b-11ea-87ca-5589573b0b0c.png)

**Comment by Severnity** [comment]
тест для проверки 
http://95.216.127.147:9200/repository/download/IRP_RunVA/11321:id/allure-report.zip!/index.html#behaviors/b6d36426d8f3d36d2d60be4bd6c94516/34661b21593159e9/
http://95.216.127.147:9200/repository/download/IRP_RunVA/11321:id/IRP_develop_1004.zip!/Forms/1Cv8.1CD

**Comment by Severnity** [comment]
перенести в обработку

**Comment by Teomit** [comment]
- [ ] 1

- [ ] 2

- [ ] 3

- [ ] 4

**Comment by DitriXNew** [comment]
теперь есть новая  форма сравнения при сканировании
