### ISSUE TITLE
Error on create GR

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1120]
Прилетает структура при созданнии. Пока вставил костыль
![image](https://user-images.githubusercontent.com/11927866/132963667-f655dc53-0077-41a9-b4ae-3711c9ed53a7.png)

**Comment by bryaleks** [comment]
выходит когда в списке документа стоит отбор
Проведен = Истина

**Comment by andreyvorobyov2** [comment]
Версия 1с какая?
в 8.3.20 вот такая ошибка, при создании сотбором всписке
![image](https://user-images.githubusercontent.com/66310255/132979077-323bd788-1c8c-4479-a2ae-cbeecc8ea31b.png)
