### ISSUE TITLE
Set modifised store data at commands

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1121]
Не забываем ставить галочку на тех коммандах, которые влияют на модификацию данных.
А то вот стоит блок на документ, типо - блокировка формы, чел не может менять табличную часть, но просканировать - без проблем. А потом это может привести к чудесам, и будем думать - как они смогли влезть в закрытый документ

![image](https://user-images.githubusercontent.com/11927866/132966429-53adf9ea-c048-4677-ac7e-b6bb38b77f5a.png)

**Comment by DitriXNew** [comment]
Это надо ставить только тем коммандам, которые могут модифицировать документ

**Comment by bryaleks** [comment]
Ну и до кучи не хорошо ставить блок на документ просто делая на форму только чтение = ложь.. так как в заказе надо поменять статус или комментарий дописать,

**Comment by andreyvorobyov2** [comment]
Если нажать на такую кнопку, то форма документа сразу же  получит признак модифицированности. 
что делать неправильно если открывается до. форма. в которой можно нажать на Cancel.

для блокировки кнопок вместе с формой нужно использовать специфльную процедуру
![image](https://user-images.githubusercontent.com/66310255/132979718-aef4f06e-59c3-4f14-a82b-0eff58dbfa4e.png)
