### ISSUE TITLE
When clone objects additional attributes dont close

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#113]
Это баг или фича что при копировании объектов не копируются доп реквизиты?
Документ purchase invoice как пример.

**Comment by DitriXNew** [comment]
@Severnity Надо написать тест на копирование доп реквизитов в документе и справочнике, можно любые взять, по одному

**Comment by DitriXNew** [comment]
И написать тест, когда есть настройка доп реквизита по умолчанию, и при копировании обхекта - если реквизит пустой, то должен ставиться из настроек пользователя, а если он заполнен, то тогда должен браться из копируемого обхекта
