### ISSUE TITLE
Fix or delete ChoiceFormWithDept

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1136]
Они нифига не открываются

**Comment by andreyvorobyov2** [comment]
DocInvoiceMatchClient

`Procedure ApTransactionsBasisDocumentChoice(Result, AdditionalParameters) Export

	If Result.Value = Type("DocumentRef.PurchaseInvoice") Then
		OpenSettings = DocumentsClient.GetOpenSettingsStructure();
		OpenSettings.FormName = "Document.PurchaseInvoice.Form.ChoiceFormWithDept";

		DocumentsClient.PurchaseInvoiceStartChoice(AdditionalParameters.Object, AdditionalParameters.Form,
			AdditionalParameters.Item, AdditionalParameters.ChoiceData, AdditionalParameters.StandardProcessing,
			OpenSettings);
	ElsIf Result.Value = Type("DocumentRef.SalesReturn") Then
		OpenSettings = DocumentsClient.GetOpenSettingsStructure();
		OpenSettings.FormName = "Document.SalesReturn.Form.ChoiceFormWithDept";

		DocumentsClient.SalesReturnStartChoice(AdditionalParameters.Object, AdditionalParameters.Form,
			AdditionalParameters.Item, AdditionalParameters.ChoiceData, AdditionalParameters.StandardProcessing,
			OpenSettings);
	Else
		Return;
	EndIf;
EndProcedure`
