### ISSUE TITLE
Indexes in Specification

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#116]
В табличных частях DataSet и DataQuantity надо у Key проставить индексацию, а так же поля Attribute и Value нужно проверить на предмет необходимости индексации.

**Comment by DitriXNew** [comment]
У кия проставил, по остальному - другую задачу надо сздать

**Comment by bryaleks** [comment]
зачем другую задачу, в этой нужно написать надо или не надо индексировать Attribute и Value. точнее если надо в этой же задаче решить, если не надо написать почему не надо и закрывать.
