### ISSUE TITLE
Posting sequence control

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1181]
Надо сделать контроль, что бы проведение например SC не было возможно если не проведен SO, который выше по цепочке

**Comment by andreyvorobyov2** [comment]
решается установкой константы Enable linked rows integrity
![image](https://user-images.githubusercontent.com/66310255/148211412-3092a224-d60e-42dd-93d6-2e673f4450d2.png)
не даст провести подчиненный документ если верхний не проведен
![image](https://user-images.githubusercontent.com/66310255/148211531-524b93fc-0ed7-404b-a73b-ceb228426ea9.png)
и отменить верхний не даст если есть проведенный ниже
![image](https://user-images.githubusercontent.com/66310255/148211660-eae2ce22-45a7-4877-bf1d-4de8a9cf8ada.png)
