### ISSUE TITLE
R3010B_CashOnHand of CP/CR/BP/BR 

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1189]
Необходимо убрать все условия по регистру R3010B_CashOnHand у документов:

- [x] BankPayment
- [x] BankReceipt
- [ ] CashPayment
- [ ] CashReceipt

**Comment by bryaleks** [comment]
Непорядок Дмитрий, задача на вас не была назначена и в спринт не была поставлена. Ай ай ай..
