### ISSUE TITLE
Message when creating another Purchase invoice/Sales invoice

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#119]
Пользователь создает Sales order/Purchase order
На его основании на частичное количество создает Purchase invoice/Sales invoice
При создании Purchase invoice/Sales invoice на оставшееся количество должно появляться сообщение 
Sales invoice is not the same as the Sales order will be due to the fact that there is already another Sales invoice that partially closed this Sales order
или 
Purchase invoice is not the same as the Purchase order will be due to the fact that there is already another Purchase invoice that partially closed this Purchase order

Раньше сообщение выводилось в одну строку, а теперь есть перенос строки. Это баг или так и должно быть?

![изображение](https://user-images.githubusercontent.com/66120736/87930586-0586a400-ca91-11ea-878f-44b4ef318f4f.png)
![изображение](https://user-images.githubusercontent.com/66120736/87931428-74b0c800-ca92-11ea-89db-9375cab826ac.png)

**Comment by DitriXNew** [comment]
Это фича

**Comment by bryaleks** [comment]
а в чем фича? в том что попап сообщение пополам разрезали?
