### ISSUE TITLE
Branch filters and controls

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1195]
- [ ] В BusinessUnits добавить реквизиты isBranch и isProfitLossCenter 
- [ ] Проставить в документах отборы по реквизитам Branch = isBranch
- [ ] Проставить в документах отборы по реквизитам ProfitLossCenter = isProfitLossCenter 
- [ ] В BusinessUnits добавить реквизиты CompanyMustMatch и Company . Если CompanyMustMatch = True выбирать Company обязательно. В документах ругаться если при наличии галочки Company в документе не сходится с Company в ProfitLossCenter или в Branch.
- [ ] Если при выборе Company есть только один подходящий Branch (где isBranch=True и не других компаний), его нужно заполнить.

**Comment by DitriXNew** [comment]
Актуально?
