### ISSUE TITLE
Registration records report

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1204]
Надо добавить в отчет по проводкам выключатель технических регистров и переключатель который уберет другие мультивалютные проводки кроме транзации

**Comment by andreyvorobyov2** [comment]
TM1010B_RowIDMovements
TM1010T_RowIDMovements
TM1020B_AdvancesKey
TM1030B_TransactionsKey	
T2010S_OffsetOfAdvances
T2013S_OffsetOfAging
T2014S_AdvancesInfo
T2015S_TransactionsInfo
T3010S_RowIDInfo
T6010S_BatchesInfo
T6020S_BatchKeysInfo
T6040S_BundleAmountValues
T6050S_ManualBundleAmountValues
T6060S_BatchCostAllocationInfo
T6070S_BatchRevenueAllocationInfo
T6080S_ReallocatedBatchesAmountValues
T6090S_CompositeBatchesAmountValues
T6095S_WriteOffBatchesInfo
T7010S_BillOfMaterials
T7051S_ProductionDurationDetails
