### ISSUE TITLE
NotActive in all not technical catalogs

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1216]
Нужно сделать галочку "не активный" у всех не технических справочников, и скрывать их их списков, списков выбора и из ввода по строке.
В меню "еще" можно добавить переключатель "Show not active".

**Comment by fanast2** [comment]
Привет!
Хочу взять эту задачу на себя. Подскажи плз с командой Show not active как лучше релизовать?

**Comment by DitriXNew** [comment]
Кейсы когда это надо дай. А то не понятно про какие именно справочники идет речь, и как вычислять не активные.

**Comment by Severnity** [comment]
вместе с задачей https://github.com/IRPTeam/IRP/issues/1850
