### ISSUE TITLE
Download options for currency rates

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#122]
Ситуация: пользователь загружает курсы валют из двух источников (в одном источнике указан прямой курс валюты, а в другой - обратный курс).
Необходимо вынести признак расчета обратного и прямого курса в справочник currency movement type. Расчет должен осуществляться по виду курса, который указан в currency movement type. При этом пользователю в самом документе может отображаться как обратный так и прямой курс, в зависимости от его настроек.

**Comment by bryaleks** [comment]
Но в документе должен быть записан именно тот курс который был загружен из сервиса. В данный момент в документе есть признак прямой или обратный и курс после изменения записывается в документ как есть.
