### ISSUE TITLE
Problem with copy of condition during coping Attribute in Additional attribute set

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#132]
При создании  копированием атрибута у Item в Additional attribute set условие не копируется, хотя значок Is condition стоит

**Comment by Severnity** [comment]
@gagmaz необходим реальный кейс

**Comment by gagmaz** [comment]
@Severnity Например, в  Additional attribute set у Item есть Attrbute Antenna Type с условием Item type = Extender
![image](https://user-images.githubusercontent.com/68659714/94245663-408ad500-ff23-11ea-9081-0db8b07e3a1a.png)

Копированием добавляю новый Attribute Other, флаг Is condition установлен, но если зайти в условие, то оно пустое
![image](https://user-images.githubusercontent.com/68659714/94246107-fbb36e00-ff23-11ea-9709-edb1e8bdea41.png)
