### ISSUE TITLE
Select serial lot number

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1337]
создаю PI и выбираю товар у которого есть серийный номер, но когда я его пробую выбрать, у меня выдает сообщение что такого серийного номера нет и программа предлагает его повторно создать
![image](https://user-images.githubusercontent.com/66120736/169492472-00c7606e-ac02-4005-b3bf-b3232c087eae.png)
![image](https://user-images.githubusercontent.com/66120736/169492524-c1849eec-0304-4364-b756-ecb15cc9519a.png)

**Comment by DitriXNew** [comment]
Это там где мы разобрались? Что загрузка не так была?
