### ISSUE TITLE
is serial description match template

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1344]
Сделать механизм проверок по регуляркам - совпадает имя с одним из шаблонов или нет

**Comment by DitriXNew** [comment]
![изображение](https://user-images.githubusercontent.com/11927866/170302882-94b5fb4d-6e74-4e38-a824-f6505c283ac7.png)
Работает только при записи нового справочника, и только если есть владелец серии.
Если перезаписать ранее созданный - контроль не выполняется.
Для работы надо расширение Additional Functionality, без него - все проверки будут по умолчанию работать как истина.
Надо убедиться что режим безопасности снят.

**Comment by Severnity** [comment]
@DitriXNew расширение Additional Functionality по умолчанию подключается?
