### ISSUE TITLE
GR/SC without ivnoices

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1352]
В некоторых случаях по поступлениям/отгрузкам товаров через GR/SC ввод инвойсов не ожидается.
Можно добавить в виды операции по одному значению с пометкой безинвойса и в таком случае не делать проводки в R1031,R4031/R2031,R4032

**Comment by andreyvorobyov2** [comment]
Какой документ будет списывать финансовую часть (стоимость товаров), если не будет инвойса?

**Comment by bryaleks** [comment]
В том то и вопрос, что в этом случае не будет финансового документа. 
Например: товар пришел от покупателя с жалобой на дефект, его отправили поставщику на исследование.
Или что то типо комиссионного товара. Консигнация это отдельный разговор конечно, но можно будет в дальнейшем развить функционал в сторону консигнации.

**Comment by andreyvorobyov2** [comment]
Комиссионый товар учитывается на балансе. Возврат товара от покупателя так же учитывается на балансе.
Если не будет финансовых документов баланс не сойдется. Стоимость товара должна либо быть долгом контрагента (покупателя\поставщика) либо упасть на расходы\доходы, подругому никак.

**Comment by DitriXNew** [comment]
Я тоже думаю что тут лучше под клиента сделать.
