### ISSUE TITLE
Copy document Sales Invoice and create RetailSalesReceipt

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#136]
- [x] Скопировать документ
- [x] Убрать из его проводок все то, что не касатеся розницы:
    - [x] Движение по взаиморасчетам
    - [x] Движение по связаным со складскими ордерами движения
    - [x] Движения связанные с заказами
- [x] Сделать движения по складским регистрам, если склад ордерный

**Comment by bryaleks** [comment]
Сделать движения по складским регистрам, если склад НЕ ордерный
