### ISSUE TITLE
Delete old code (StatusStartChoice)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1377]
Необходимо удалить процедуру StatusStartChoice (не используется)
IRP/src/CommonModules/ObjectStatusesClient/Module.bsl

**Comment by DementorAK** [comment]
@Severnity Процедура ObjectStatusesClient.StatusStartChoice() используется в обработчике события "Begin selection" колонки "Status" на форме справочника ObjectStatuses.

Нужно ли удалить этот обработчик и использовать стандартные механизмы выбора?

![image](https://user-images.githubusercontent.com/5967038/195381933-f49bdc69-19e8-4b80-8340-425be8f374d6.png)
![image](https://user-images.githubusercontent.com/5967038/195381638-ca2bbe6f-f1f2-443f-af13-d330014cab09.png)

**Comment by DementorAK** [comment]
Выше упомянутый код действительно был устаревшим. При попытке выбрать статус срабатывает установка фильтра, которая указана в параметрах выбора элемента формы. Этот код действительно был не нужен и я уже сделал пуллреквест на его удаление.

@Severnity но, как даже видно на скриншоте выше, у колонки был еще один обработчик - при редактировании текста. Этот обработчик вызывает функцию ObjectStatusesClient.StatusEditTextChange(), которая не работает ожидаемым образом! При попытке не выбирать статус из выпадающего списка, а ввести его текстом - ничего не получается, нет совпадений.
![image](https://user-images.githubusercontent.com/5967038/196434561-ff5fa635-8d15-4910-8e41-d727185b1894.png)
