### ISSUE TITLE
Payments in RSR/RRR

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1394]
В розничных продажах и возвратах.
1. При изменении PaymentType и BankTerm надо проверять % комиссии из BankTerm и при необходимости подставлять % и пересчитывать сумму комиссии. Если по данному PaymentType нет записи в BankTerm ставить % = 0
2. При изменении Amount надо пересчитывать сумму комиссии.
3. Чтобы Payment Type можно было выбрать только из доступных Bank Term. Также надо поменять очередность реквизитов, сначала BankTerm потом PaymentType, а PaymentTerminal в самый конец

**Comment by DitriXNew** [comment]
В RetailReturnReceipt в payments добавить BankTerm
