### ISSUE TITLE
Pos/Cash movements

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1400]
- [x]  добавить возможность получать оплату от клиента и делать возврат по POS в BR/BP.
В BR +PaymentFromCustomerByPos в BP +ReturnToCustomerByPos. При этих видах операции надо также иметь возможность указывать BankTerms, PaymentType и PosTerminal. Так же как и RSR/RRR проводки падают в регистр R3050T_PosCashBalances и R3010B_CashOnHand.
- [x]  в документе BR с видом from pos надо сделать признак того, включает ли сумма комиссию или нет. разные банки по разному отражают проводки, некоторые сначала делают приход 100, а потом отдельной строкой списывают %, а некоторые сразу делают приход 98, то есть за вычетом комиссии. От этого признака зависят проводки по касссе и по деньгам в пути.
- [x]  В CashAccount с видом POS надо добавить возможность выбирать счет, куда упадут деньги снятые с пос терминала, а также галочку CommissionIsSeparate, которая будет регламентировать отражается ли комиссия отдельной строкой или сумма на счет падает сразу за вычетом комиссии.
- [x]  В CashStatement необходимо реализовать "закрытие" регистра R3050T_PosCashBalances. Берутся (!) обороты за день и перекидываются на деньги в пути. Также в CS надо иметь возможность указать счет, на который в итоге упадет сумма по посу (подставлять из предыдущей задачки).
- [x] В регистрах деньги в пути надо добавить данные по счету, куда деньги собираются упасть, и добавить проводки в CS.
- [x] В RRR если в видах оплаты указан Pos - деньги падают на R3050T_PosCashBalances, если Bank и стоит новая галочка "PostponedPayment" тогда на деньги в пути, если галочка не стоит, тогда расход с R3010B_CashOnHand
- [ ] Сделать более "удобным" подбор документов в BR/BP с видом операции from pos/to pos. Сейчас просто открывается список CS. По идее надо делать отбор по остаткам денег в пути по счету, выбранному в документе и показывать в списке выбора сумму, сумму остатка, сумму комиссии. Также сделать отборы "показать все", "только вчерашние".

![image](https://user-images.githubusercontent.com/32883592/175078381-52378e37-2d12-4476-8621-f662c2ac6304.png)

**Comment by Severnity** [comment]
последний пункт вынесен в отдельную задачу
https://github.com/IRPTeam/IRP/issues/1421
