### ISSUE TITLE
New print form

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1436]
Создать общую форму для печати.

**Comment by Severnity** [comment]
- [ ] посмотреть почему пропали кнопки редактирования и вернуть обратно
- [ ] по умолчанию количество 1, 1 символ
- [ ] выводить синоним в name template
- [ ] по двойному щелчку по документу открывать сам документ
- [ ] вместо представления Object и просто Edit
- [ ] убрать запись прописью
- [ ] переключатель языка макетов и данных
- [ ] поменять местами айтем и айтем ки в макете

**Comment by vBAZIL** [comment]
- [ ] вывести ставки налогов по колонкам как в документе
- [ ] вывести скидку 
- [ ] вывести в подвале  1 Net amount  2 Total tax 3 Total amount 4 Offers amount

**Comment by vBAZIL** [comment]
[ ] Сделать функцию в которую можно передать ссылку язык она вернет ссылку на этом языке (SelectionHeaderTAX[It].TaxDescription)
[ ] по выделеным строкам менять язык и данные
[ ] скрывать настройки если в форму веведен один документ
[ ] печать из Ratail - "Point of sale" - "Print last receipt"
[ ] переработать выведение парметров макета с вынесением в функции запрос и заполнение по кейсам (Добавить что то в шапку, добавить что то в строку, добавить что то в макет(табличка ниже, например курс валют)
