### ISSUE TITLE
User default setting at workstations

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1451]
Пользователь работает на разных складах или в разных магазинах, в зависимости от рабочего места должны меняться настройки пользователей по умолчанию.

В справочник workstations надо добавить реквизит DefaultUserGrup и если заполнен Workstation в параментрах сеанса и заполнен DefaultUserGrup тогда брать настройки по умолчанию из регистра UserSettings по этой группе.

Таким способом не нужно будет на каждый магазин создавать отдельного пользователя

**Comment by DitriXNew** [comment]
Когда получается настройки пользователя, то смотри - есть ли группа у воркстейшн, если есть - ставит ее.
Для удобства - в списке воркстейшнов можно менять воркстейин кнопочкой сверху. При изменении - настройки сбрасываются, так что перезаходить в базу не надо.

**Comment by Severnity** [comment]
@bryaleks сейчас работает так:
1. если настройки установлено лично для пользователя, то эти настройки будут в приоритете в не зависимости от группы в вокрстейшин
2. если настроек лично у пользователя нет и группа настроек для пользователя отличается от той которая в вокрстейшин, то настройки возьмутся из группы в воркстейшин
3. если группа настроек в воркстешин не установлена, но есть у пользователя, то настройки возьмутся из группы пользователя
