### ISSUE TITLE
Legal name in the Partner term (problem with filters)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1455]
1. Выбираем подчиненного партнера
![image](https://user-images.githubusercontent.com/66120736/183984110-fe83df32-0c97-46d7-b166-696c8f72c4bd.png)
2. По нему была создана своя компания, но она помечена на удаление
![image](https://user-images.githubusercontent.com/66120736/183984283-f1912e7c-d7f0-47df-a019-e5b765d6e38d.png)
3. При создании Partner term не дает выбрать компанию главного партнера 
![image](https://user-images.githubusercontent.com/66120736/183984545-b11a2067-fe10-42f2-8804-4fa117965770.png)

**Comment by DementorAK** [comment]
Причина ошибки:
1) В списке выбора устанавливается фильтр ПометкаУдаления=Ложь
2) Показываются не все "Legal name" по партнерской иерархии, а только те, которые находятся на уровне, который максимально близок к выбранному Партнеру. Пометка удаления при этом не анализируется и видимо предполагалось показывать даже помеченные на удаление элементы.

Я сейчас быстро могу исправить, если добавлю в анализ уровней проверку на ПометкаУдаления=Ложь. 

Но нет ли другого решения? Допустимы ли сценарии, что при выборе подчиненного Партнера нужно выбирать не только его "Legal name", но и те, которые подчинены вышестоящим элементам?

**Comment by Severnity** [comment]
> Причина ошибки:
> 
>     1. В списке выбора устанавливается фильтр ПометкаУдаления=Ложь
> 
>     2. Показываются не все "Legal name" по партнерской иерархии, а только те, которые находятся на уровне, который максимально близок к выбранному Партнеру. Пометка удаления при этом не анализируется и видимо предполагалось показывать даже помеченные на удаление элементы.
> 
> 
> Я сейчас быстро могу исправить, если добавлю в анализ уровней проверку на ПометкаУдаления=Ложь.
> 
> Но нет ли другого решения? Допустимы ли сценарии, что при выборе подчиненного Партнера нужно выбирать не только его "Legal name", но и те, которые подчинены вышестоящим элементам?

Сейчас предусмотрены следующие сценарии:
Есть главный партнер А и к нему главный контраент B
У партнера А есть подчиненные партнеры
1-й вариант: у подчиненных партнеров есть свой контрагент - тогда заполняется контрагент из подчиненного партнера
2-й вариант: у подчиненного партнера нет своего контрагента - тогда заполняется контрагент из главного партнера (тоесть контрагент B)
