### ISSUE TITLE
GR - when changing TransactionType not clearing Partner and LegalName

### ISSUE THREAD

**Issue by andreyvorobyov2** [IRPTeam/IRP#1460]
При изменении Transaction type в документе Goods receipt не очищаются поля относящиеся к прежнему TransactionType
![image](https://user-images.githubusercontent.com/66310255/184143891-7713eb6d-e387-4383-9c86-041d9bfc5088.png)

**Comment by DementorAK** [comment]
Аналогично в ShipmentConfirmation
