### ISSUE TITLE
Unfilled mark in serial lot numbers

### ISSUE THREAD

**Issue by andreyvorobyov2** [IRPTeam/IRP#1464]
в документах после заполнения серийных номеров отметка незаполненного остается
![image](https://user-images.githubusercontent.com/66310255/184361094-4971b032-4959-433c-aaa6-86716302acc7.png)

**Comment by DitriXNew** [comment]
А там количество все совпадает?

**Comment by andreyvorobyov2** [comment]
![image](https://user-images.githubusercontent.com/66310255/184361683-bebe8ba9-8713-4a70-b196-d444e3e0eaa3.png)
![image](https://user-images.githubusercontent.com/66310255/184361722-8d2b8807-113e-4c11-b5ae-e0a6e6998ce2.png)

**Comment by Severnity** [comment]
это в каком документе? мы вроде это чинили

**Comment by DitriXNew** [comment]
Это везде так? Во всех доках? И сразу после добавления? Или после записи?

**Comment by andreyvorobyov2** [comment]
в SI есть, остальные не смотрел

**Comment by andreyvorobyov2** [comment]
там от количества не зависит, пометка при открытии устанваливается и не меняется пока не переоткрыть документ
![image](https://user-images.githubusercontent.com/66310255/184363227-401d7a38-faa7-4558-aef6-85c9eb3fa7f0.png)
![image](https://user-images.githubusercontent.com/66310255/184363262-6e704c78-a465-43eb-b724-9ffd84066f60.png)

**Comment by DitriXNew** [comment]
Косяк когда ты выбираешь количество в серийниках отличное от количества в документе.
А потом мы меняем количество в документе на нужное, и по идее - должен перерасчитать этот признак, но он не пересчитывается.

**Comment by andreyvorobyov2** [comment]
Серийные номера левее поэтому сперва выбираются серийные номера а потом вводится количество.

**Comment by DitriXNew** [comment]
Да, поэтому и говорю, что косяк есть.
@Severnity А тестом это можно покрыть?

**Comment by Severnity** [comment]
> Да, поэтому и говорю, что косяк есть. @Severnity А тестом это можно покрыть?

если отображалку, то нет

**Comment by Severnity** [comment]
разве что может можно как-то кодом проверить?

**Comment by DitriXNew** [comment]
кодом не выйдет, так как это форма
