### ISSUE TITLE
Bugs with Print labels DataProcessor

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1471]
- [x] при нажатии на кнопку Fill возникает ошибка
![image](https://user-images.githubusercontent.com/66120736/184829115-67a2e1d0-751c-416a-ac46-a0ea8e00544e.png)

- [ ] при изменении вида цен цена не меняется
![image](https://user-images.githubusercontent.com/66120736/184829498-5b1a958c-c46d-4dcf-813a-c7c225251629.png)

- [x] нерабочие кнопки
![image](https://user-images.githubusercontent.com/66120736/184829820-fbe35209-ad64-4650-9cd1-d8daaddafec5.png)

**Comment by DementorAK** [comment]
@Severnity  пункт №2 по описанию не воспроизводится - цена изменяется
![GIF 12 10 2022 14-44-11](https://user-images.githubusercontent.com/5967038/195334759-f34a2e4f-e486-4acf-88a6-204be646b501.gif)

**Comment by DementorAK** [comment]
@Severnity пункт №3 по описанию не воспроизводится - сохранение и восстановление работают:
![GIF 12 10 2022 14-48-51](https://user-images.githubusercontent.com/5967038/195335298-37cac418-4577-4276-903b-d1065878f105.gif)

**Comment by Severnity** [comment]
@DementorAK проверила второй пункт, цена так и не изменяется при изменении вида цен. Попробуй поменять Basic Price without VAT, цена должна стать 466,10

**Comment by DementorAK** [comment]
Ответы на мои вопросы для истории:
1. Да, действие установки только для выделенных строк.
2. По реквизиту нет консенсуса. Сделаю по аналогии с установкой типа цены. Уже есть установка в строки при выделении, нужно добавить установку при полном заполнении.
3. Переделал на логику IRP - сначала единица измерения берется из ItemKey, но если там пусто, то из ItemKey.Item
4. Это ошибка к исправлению.
5. На обработке смесь старой и новой логики. Нужно переделать на использование функции GetInfoByItemsKey()
