### ISSUE TITLE
Discount amount

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1500]
В розничном чеке цена 1 шт 10 599,00, документ включает НДС = Истина.
Делаю скидку 100 на акцию А, применяю. Затем делаю еще одну скиду на 150 по акции Б, сумму ставит 249,63.
Но при указании обеих скидок правильно рассчитывает. В справочнике скидок групп нет.

**Comment by DitriXNew** [comment]
https://github.com/IRPTeam/ExternalDataProcessors/issues/7

**Comment by DitriXNew** [comment]
Исправил, там надо пару строк местами поменять
https://github.com/IRPTeam/ExternalDataProcessors/commit/471a477a6a8060a29bc1ddea682f80a9fc9a4621
