### ISSUE TITLE
Error when start enter text at fast filter field

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1512]
Вывести фильтр по справочникам в любой форме и ввести код для поиска.
```
Error running processor - 'ChoiceDataGetProcessing'
, reason:
Invalid parameter value (parameter number '1')
{CommonModule.CommonFormActionsServer.Module(160)}:            NewFilter = QueryBuilder.Filter.Add("Ref." + Filter.Key);

, reason:
Invalid parameter value (parameter number '1')
```

![изображение](https://user-images.githubusercontent.com/11927866/190928560-294fbcb3-db2e-474b-a30a-bbd442f845d1.png)

**Comment by andreyvorobyov2** [comment]
исправлена и эта ошибка
![image](https://user-images.githubusercontent.com/66310255/191004591-798ccefc-7d8b-41ae-988b-ab08939fa770.png)
