### ISSUE TITLE
Subsystem icons changes

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#152]
Необходимо заменить иконки подсистем для того чтобы все они были в едином стиле.
Архив с иконками прилагается (наименование иконки соответствует подсистеме)
[icons.zip](https://github.com/IRPTeam/IRP/files/5020307/icons.zip)

**Comment by DitriXNew** [comment]
![image](https://user-images.githubusercontent.com/11927866/89542523-a45f1000-d7b4-11ea-8136-865fb63f3515.png)
