### ISSUE TITLE
Exist in user list boolean in user list and password change

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1522]
В списке пользователей необхожимо вывести признак, по которому будет понятно есть ли данный пользователь с списке пользователей базы данных. Со временем пользователи удаляются из списка в конфигураторе, а в списке пользоветелей не понятно.

Также необходимо реализовать функционал замены пароля пользователя.
Если в у пользователя проставлена галочка ChangePasswordOnNextLogin тогда после входа в систему пользователю выводится окошко замены пароля.

**Comment by DitriXNew** [comment]
Скорее всего надо добавить в пользователей галочку Disable, и если она стоит, то удалять пользователя из списка. Из конфигуратора ничего удалять не надо

**Comment by DementorAK** [comment]
@Severnity в этой задаче остался только глюк со сбросом ролей при повторной деактивации, или еще что-то?

**Comment by Severnity** [comment]
> @Severnity в этой задаче остался только глюк со сбросом ролей при повторной деактивации, или еще что-то?
и ещё функция замена пароля не реализована (второй пункт задачи)
