### ISSUE TITLE
Subsystems order

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1524]
Purchase - A/P
Sales - A/R
Retail
Inventory
Treasury
Manufacturing
Master data
Reports
Settings

Mobile и Admin function надо скрыть

**Comment by DementorAK** [comment]
@bryaleks подсистема Manufacturing сейчас не существует, но вместо нее есть WorkOrders - это одно и тоже?
На какие места нужно поставить Accounting, Settings и Saas?
![image](https://user-images.githubusercontent.com/5967038/195388963-cf0ba272-3b3c-46c1-a7dd-b786fc272131.png)

**Comment by Severnity** [comment]
@DementorAK Manufactoring сейчас в отдельной ветке (пока эту подсистему не трогай). С work order это разные вещи.
Accounting и  Saas можно скрыть, Settings должны быть под Reports в самом низу
