### ISSUE TITLE
Choosing basis doc in payment documents

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1530]
При учете оплат по документам очень неудобно выбирать документы в BR/BP/CR/CP
Желательно что бы выбранные уже документы не выходили в списке, если сумма остатка по документу уже закрыта в текущем документе

**Comment by andreyvorobyov2** [comment]
в общем модуле 
`JorDocumentsServer`
строку 15 
`Period = New Boundary(Ref.PointInTime(), BoundaryType.Excluding);`
заменить на 
`Period = New Boundary(Ref.PointInTime(), BoundaryType.Including);`

**Comment by bryaleks** [comment]
> 1. Если случайно уберут строку с ранее использованным документом, то не смогут ее вернуть не отменив проведение. >А если отменять проведение, то старое и новое поведение будут идентичны.

Тут особо ничего не сделаешь, без тройного сальто. Мне кажется что стоит опустить момент того, что удаленная строка проведенного документа не будет появляться в списке. Ну или напоминать что надо распровести документ, что бы данная строка снова появилась в списке к выбору.

**Comment by DementorAK** [comment]
@bryaleks сейчас при выборе документа оплаты работает следующая логика для показа остатка долга:
1. Если документ еще не записан, то берется долг на текущий момент, даже если делают документ за прошлые периоды.
2. Если платежный документ записан, но не проведен, то берется долг на конец дня даты, которая указана в документе.
3. Если платежный документ записан и проведен, то берется долг на момент перед документом, чтобы не учитывать его движения.

**Оставляем эту логику?** 
Или делать как проговаривали на встрече - для всех документов и новых и старых показывать в журнале подбора остаток долга на текущий момент, а если документ проведен, то компенсировать его движения?
**Ключевое:** хотим или нет видеть остатки взаиморасчетов по документам, которые делали после дат авансовых платежей?

**Comment by bryaleks** [comment]
> **Оставляем эту логику?** Или делать как проговаривали на встрече - для всех документов и новых и старых показывать в журнале подбора остаток долга на текущий момент, а если документ проведен, то компенсировать его движения? 
**Ключевое:** хотим или нет видеть остатки взаиморасчетов по документам, которые делали после дат авансовых платежей?

Мне кажется, что лучше сделать переключатель в форме выбора "ByDocumentDate"/"All". Потому что в некоторых случаях надо все таки иметь возможность указать документ, который введен датой позже.
Логику можно немного подправить. Сделать так, что бы в списке выбора не учитывались проводки текущего документа, но в форму выбора передавались документы и суммы оплат, для того что бы или убрать или уменьшить сумму остатка в форме выбора.

**Comment by DementorAK** [comment]
@bryaleks как именно должен работать механизм ByDocumentDate - как и сейчас? Т.е. для не проведенных документов на конец дня документа, а для проведенных "за мгновение До"? Или всегда на секунду документа, даже если не проведены?
