### ISSUE TITLE
Clear field Number in Catalog CashAccounts with type POS

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#1564]
Если CashAccount с типом POS, то система при сохранении очищает поле Number. У POS оно нужно для указания их номеров, через которые идет привязка к банковским выпискам.

![image](https://user-images.githubusercontent.com/68659714/197795271-d218cca3-cf04-48de-aa5c-b985dc367251.png)

**Comment by DitriXNew** [comment]
Там стоит проверка, что очищается все, если это не банковский счет. Наверное тут надо пределать, и не выводить его на форму, ну а при записи он очищается, так как его не может быть у кассы.
