### ISSUE TITLE
Add Title at columns name in dynamic list

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#157]
Пример - есть запрос в списке валют, там есть поле запросе динамического списка Description.
Заголовка у полей нет, поэтому на всехязыках оно будет как Description, поэтому в случае, когда данные вытягиваются из запроса и выводятся на форму - надо обязательно заполнять заголовки

**Comment by Severnity** [comment]
создана ещё одна задача https://github.com/IRPTeam/IRP/issues/579
