### ISSUE TITLE
Related documents

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1572]
Необходимо сортировать документы по дате и желательно вывести рядом дату последнего изменения.
![image](https://user-images.githubusercontent.com/32883592/198521183-0f50a063-eb0e-4cce-9e38-5a3aeb03d9d4.png)

**Comment by DementorAK** [comment]
@bryaleks  Сортировку я уже делал ранее по задаче #1861 
А что это за "дата последнего изменения"? У нас же нет такого общего реквизита. Или тут о чем-то другом речь?
