### ISSUE TITLE
POS refact

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1579]
Переделать POS, надо сделать красивую форму старта, открытия кассовой смены, закрытия и т.д.

**Comment by Severnity** [comment]
в рабочем месте определять есть ли фискальник
если это не касса ККМ, то на форме РМК изъятие и внесение не показывать

настройка использования ОРП остается в бизнес юните

**Comment by DitriXNew** [comment]
![изображение](https://user-images.githubusercontent.com/11927866/200575769-c56870e6-58f6-4b6f-bc58-4e71c48fe702.png)

**Comment by DitriXNew** [comment]
![изображение](https://user-images.githubusercontent.com/11927866/200575859-15af21df-5958-4c2e-8515-c73e142b8eb1.png)

**Comment by DitriXNew** [comment]
![изображение](https://user-images.githubusercontent.com/11927866/200575922-595ac4af-6f3f-4be5-8951-39418f1e6725.png)

**Comment by DitriXNew** [comment]
![изображение](https://user-images.githubusercontent.com/11927866/200575984-af1d2bf8-ce34-4ebb-b4cc-9fbdd700b5bb.png)

**Comment by DementorAK** [comment]
@DitriXNew @Severnity все эти "я не дурак" и фактические данные, которые вручную вносят с оборудования - нужно ли это сохранять в базу? Или это чистый самоконтроль без последствий для кассиров, которые будут бездумно прокликивать "далее-далее"?

**Comment by Severnity** [comment]
> @DitriXNew @Severnity все эти "я не дурак" и фактические данные, которые вручную вносят с оборудования - нужно ли это сохранять в базу? Или это чистый самоконтроль без последствий для кассиров, которые будут бездумно прокликивать "далее-далее"?

да, эти данные потом должны будут заполниться либо в документ ConsolidatedRetailSales либо в Cash statement

**Comment by Severnity** [comment]
@DementorAK данные которые будет вводить кассир сохраняем в ConsolidatedRetailSales (отдельная таблица без феншуев и без проверок)

**Comment by DementorAK** [comment]
@Severnity есть ли какие-то конкретные требования к сохраняемых данным или снова все на мое усмотрение?

**Comment by Severnity** [comment]
> @Severnity есть ли какие-то конкретные требования к сохраняемых данным или снова все на мое усмотрение?

на твое усмотрение чтобы было как можно менее трудозатратно
