### ISSUE TITLE
Wrong header when creating Payment terminal

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#160]
Неверный заголовок окна создания элемента справочника Payment terminal
Должен быть заголовок Payment terminal (представление объекта)
![изображение](https://user-images.githubusercontent.com/66120736/89427181-a1780700-d743-11ea-87cb-06e97bc375fb.png)

**Comment by andreyvorobyov2** [comment]
Исправлено, в комите не указан номер задачи

![image](https://user-images.githubusercontent.com/66310255/90682003-fc921980-e26c-11ea-9f78-328ba764e4b6.png)
![image](https://user-images.githubusercontent.com/66310255/90682264-60b4dd80-e26d-11ea-8b5d-e267fa5d7f26.png)
