### ISSUE TITLE
Filling legal name and partner term in new document by partner

### ISSUE THREAD

**Issue by Teomit** [IRPTeam/IRP#164]
Не заполняется Legal name и Partner term по Partner при создании нового документа. Необходимо перевыбирать Partner. Ошибка обнаружена по документу Retail sales receipt.

**Comment by Teomit** [comment]
Необходимо уточнить логику заполнения.

**Comment by Severnity** [comment]
сделать так чтобы при заполнении Partner из настроек выполнялось при изменении
