### ISSUE TITLE
Cash payment type in Retail sales receipt

### ISSUE THREAD

**Issue by Teomit** [IRPTeam/IRP#168]
Решили, что сдача с наличных оплат должна учитываться. И, в дальнейшем планируется поддержка обналичивания банковских карт. Необходимо решить как будет выбиратся вид оплаты с типом "Cash", если их будет несколько.

**Comment by bryaleks** [comment]
Предлагаю реализовать похожий механизм, который реализован для оплаты по карте, но местом установки настроек можно сделать справочник настройек рабочего места.

В обычной ситуации в розничном магазине не может быть несколько видов оплат наличными. Но в не обычной ситуции, например когда наличные принимаются неколькими валютами, под кнопкой наличные можно разместить "развилку" для выбора какая именно валюта. А так как нужно дать возможность настроить одну из нескольких касс многовалютной, опять же приходим к тому что в справочнике настройки рабочего места этой настройке как раз самое место.

То есть можно сделать табличную часть, в которой указывать вид оплаты и рядом валюту и кассу.

**Comment by Teomit** [comment]
Пока выбирается один тип "Cash". "Cash Account" заполняется из рабочего места.
