### ISSUE TITLE
Consolidated retail sales in the Money Transfer

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1686]
При создании изъятия из POS в Money Transfer не заполняется текущий Consolidated retail sales и из-за этого не срабатывает команда Print cash out
![image](https://user-images.githubusercontent.com/66120736/212866960-c4a05b67-600c-47f2-8db4-07f708548821.png)

**Comment by Severnity** [comment]
по аналогии как в документе Cash receipt

**Comment by DementorAK** [comment]
@Severnity можно тестировать: https://github.com/IRPTeam/IRP/pull/1692
