### ISSUE TITLE
Payment types (fiscal printer)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1687]
- [ ] при проведении аванса от клиента чек не выводится

Схема проведения аванса:

1. В POS выбираем розничного клиента
2. Нажимаем на кнопку Advance
3. Вводим сумму аванса и нажимаем на кнопку Enter

Также необходимо определить на какой вид оплаты по фискалке это должно попадать

- [ ] при зачете аванса от клиента сейчас оплата попадает как Cash или ElectronicPayment. Это правильно?

**Comment by DitriXNew** [comment]
1. RRN подставлять автоматом при возврате
2. Не давать сделать Отмену, если RRN пустой, и очищать RRN после этого.
3. Если возврат и пустой RRN то давать провести такой возврат
4. Добавить реквизиты PaymentInfo  в возврат
5. В банковских документах надо скрывать кнопку Оплаты терминала, если вид операции не POS
