### ISSUE TITLE
New DetailsPreview field

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#169]
Добавить информационное поле сверху от товаров (DetailsPreview). При активизации строки в это информационное поле нужно выводить информацию о пропиканом или добавленом товаре.
Item+ItemKey+Quantity+Price+Offer+Total

**Comment by Severnity** [comment]
@bryaleks по этой задачке может ещё сумму налога выводить чтобы математика сходилась когда цена без НДС установлена?
![изображение](https://user-images.githubusercontent.com/66120736/90641389-db640580-e239-11ea-9e19-53e2d235e7a5.png)

**Comment by bryaleks** [comment]
@Severnity тут суммы налогов не нужны, так ккак все суммы должны бать включая ндс. 
Ставка налога нужна только для визуального контроля что НДС подтянулся.

**Comment by Severnity** [comment]
@Teomit при изменении количества или цены, строка не перезаполняется
![изображение](https://user-images.githubusercontent.com/66120736/91279795-9fc3c100-e78e-11ea-965a-2453fd1e367c.png)
