### ISSUE TITLE
Generate button basis doc in orders

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#17]
В документы Sales return order, Sales return, Purchase return order, Purchase return необходимо добавить кнопку заполнения документов-основания
Например,
1. Пользователь создает Sales return order
2. Заполняет товар
3. Нажимает на кнопку Select basis documents
4. Открывается окно в котором пользователь может выбрать документы основания для возврата или товар из них который он хочет включить в возврат. Если товар в возврат уже добавлен, то для выбора должны отобразиться только те документы-основания, которые его содержат. 
Цены в документы возврата должны переносится из документа основания.
Товар, по которому уже был произведен возврат, высвечиваться повторно для возврата пользователю не должен.

**Comment by bryaleks** [comment]
потеряло актуальность
