### ISSUE TITLE
Exemple for create atributes at form from code

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#171]
Скинь примеры создания разных реквизитов с разными типами данных.

**Comment by bryaleks** [comment]
//************* Unit price in tabular section ItemList
	NewFormColumn = Items.Add("ItemListUnitPrice", Type("FormField"), Items.ItemList);
	NewFormColumn.Type = FormFieldType.InputField;
	NewFormColumn.DataPath = "Object.ItemList.MYM_UnitPrice";
	NewFormColumn.SetAction("OnChange", "RecalculatePrice_AfterUnitPriceChange");
	
	//************* Total quantity in tabular section ItemList
	NewFormColumn = Items.Add("ItemListUnitQuantity", Type("FormField"), Items.ItemList);
	NewFormColumn.Type = FormFieldType.InputField;
	NewFormColumn.DataPath = "Object.ItemList.MYM_TotalQuantity";
	NewFormColumn.ReadOnly	= True;
	NewFormColumn.FooterDataPath = "Object.ItemList.TotalMYM_TotalQuantity";
	
	//************* new command to fill tabular section ItemList from Excel
	NewCommAnd = ThisObject.Commands.Add(MYM_CommonModuleServerCall.GetUniqueName("DownloadFromExcel"));
	NewCommand.Action = "DownloadFromExcelAfter";
	NewCommand.ModifiesStoredData = True;
	
	NewButton = Items.Add(MYM_CommonModuleServerCall.GetUniqueName("DownloadFromExcel")
						, Type("FormButton")
						, Items.ItemList.CommandBar);
	NewButton.CommandName 		= NewCommand.Name;
	NewButton.Representation 	= ButtonRepresentation.Text;
	NewButton.Title = "Excelden doldur";
	//***************************************************
	NewCommAnd = ThisObject.Commands.Add(MYM_CommonModuleServerCall.GetUniqueName("SetUnitPrices"));
	NewCommand.Action = "SetUnitPricesClient";
	NewCommand.ModifiesStoredData = True;
	
	NewButton = Items.Add(MYM_CommonModuleServerCall.GetUniqueName("SetUnitPrices")
						, Type("FormButton")
						, Items.ItemList.CommandBar);
	NewButton.CommandName 		= NewCommand.Name;
	NewButton.Representation 	= ButtonRepresentation.Text;
	NewButton.Title = "Birim fiyatları kontrol et";

	//************ sipariş birleştir
	NewCommAnd = ThisObject.Commands.Add(MYM_CommonModuleServerCall.GetUniqueName("CombineOrders"));
	NewCommand.Action = "CombineOrdersClient";
	NewCommand.ModifiesStoredData = True;
	
	NewButton = Items.Add(MYM_CommonModuleServerCall.GetUniqueName("CombineOrders")
						, Type("FormButton")
						, Items.ItemList.CommandBar);
	NewButton.CommandName 		= NewCommand.Name;
	NewButton.Representation 	= ButtonRepresentation.Text;
	NewButton.Title = "Sipariş birleştirme";
	
	//************* add footer and put total of quantity
	Items.ItemList.Footer = True;
	Items.ItemListQuantity.FooterDataPath = "Object.ItemList.TotalQuantity";
	
	//************* 
	Items.ItemListItemKey.SetAction("StartChoice", "mym_ItemListItemKeyStartChoice");

	//SAVE PİCTURES
	NewCommAnd = ThisObject.Commands.Add(MYM_CommonModuleServerCall.GetUniqueName("SavePictures"));
	NewCommand.Action = "SavePicturesClient";
	//NewCommand.ModifiesStoredData = True;
	
	NewButton = Items.Add(MYM_CommonModuleServerCall.GetUniqueName("SavePictures")
						, Type("FormButton")
						, Items.FormCommandBar);
	NewButton.CommandName 		= NewCommand.Name;
	NewButton.Representation 	= ButtonRepresentation.Text;
	NewButton.Title = "Resimleri kaydet";
