### ISSUE TITLE
Tool for filling documents according to another documents

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#1731]
Здравствуйте, нужна обработка, которая позволит заполнять табличную часть Товары и Серийные номера одного документа на основании другого документа, а именно такие поля как Item, ItemKey, Serial Number, Quantity. На настоящий момент остро стоит необходимость заполнение документа Inventory Transfer на основании GoodReceipt, но было бы хорошо, если бы это был универсальный инструмент, который позволил бы работать с разными типами документов (SI, PI, SR, PR и т.д.)

**Comment by DitriXNew** [comment]
Копи паста работает только в тех документах где прописана (хотя пока что кнопки везде отображаются, скоро уберу)
Работает только с табличной частью ItemList
Копирует только товар, характеристику, серии, количество, единицу изменения
После копирования строк - появляется сообщение справа внизу - что скопировано столько то строк
Вставка всегда добавляет строки ниже, не группируя их
После вставки - система сбрасывает буфер

**Comment by DitriXNew** [comment]
Добавил в:
InternalSupplyRequest
InventoryTransferOrder
ItemStockAdjustment
PlannedReceiptReservation
PurchaseInvoice
PurchaseOrder
PurchaseOrderClosing
PurchaseReturn
PurchaseReturnOrder
RetailReturnReceipt
RetailSalesReceipt
SalesOrder
SalesOrderClosing
SalesReportFromTradeAgent
SalesReportToConsignor
SalesReturn
SalesReturnOrder
ShipmentConfirmation
StockAdjustmentAsSurplus
StockAdjustmentAsWriteOff
Unbundling

**Comment by DitriXNew** [comment]
Тесты:
SalesOrder - SalesInvoice
SalesInvoice - SalesOrder
PhysicalInventory - SalesInvoice
SalesInvoice - PhysicalInventory
PhysicalInventory - SalesOrder 
SalesOrder - PhysicalInventory 
PhysicalInventory  - PhysicalCountByLocation
