### ISSUE TITLE
Interface enhancement in POS

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1745]
- [x] при проведении возврата после выбора документа основания в информационном блоке необходимо группировать виды оплат

![image](https://user-images.githubusercontent.com/66120736/219407170-59da3d7a-53fe-4e53-a1aa-639548361a64.png)

- [x] после проведения возврата аванса из POS необходимо сбрасывать режим возврата (должен отображаться режим продажи)
![image](https://user-images.githubusercontent.com/66120736/219407498-486f34ae-fffe-4777-a333-8dae35c0d44c.png)

- [x] если смена не открыта, то кнопки внесения, изъятия и отчета без гашения должны быть недоступны
![image](https://user-images.githubusercontent.com/66120736/219407797-ee182fd6-6fbc-497c-bafe-46e1137430cf.png)

**Comment by DitriXNew** [comment]
Х отчет тоже скрываю если сессия не открыта
