### ISSUE TITLE
Tool for filling price in document PriceList

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#1749]
Нужно чтобы в документе PriceList пользователь вставить в каком-то предварительном окошке Code of ItemKey и Цену, система ему покажет предварительный результат со списком товаров и новых цен. Если всё ок, то пользователь переносить эти данные в табличную часть PriceList легким движением руки.

**Comment by DitriXNew** [comment]
Сделать через механизм загрузки из табличного документа
