### ISSUE TITLE
Keybord shortcuts for payment

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#175]
Подвязать shortcut для быстрого ввода оплаты

Payment (Num+)
Цифры 0-9 (0-9)
Оплата картой (*)
Оптала налом (/)
Запятая (,) - учитывать что где то запятая где то точка
Сторно С (Backspace)
Enter (Enter)

Цель: после того как товар пропикан, нужно иметь возможность ввести оплату только клавиатурой, а точнее numpad'ом.

**Comment by bryaleks** [comment]
Заменил DELETE у кнопкти Сторно С на BackSpace

**Comment by bryaleks** [comment]
Задача выполнена не по заданым условиям

**Comment by Teomit** [comment]
Для клавиши C используется shortcut Delete.
Появилась клавиша Backspace. Для неё используется shortcut BackSpace.
Для клавиши Enter нельзя назначить shortcut Enter. Однако, данная клавиша становится активной после различных действий, поэтому на ней срабатывает Enter. Также это клавиша по умолчанию, поэтому для неё работает shortcut Ctrl+Enter.

**Comment by Teomit** [comment]
В форме выбора подвида оплаты, например когда несколько банковских, для кнопок оплаты автоматом назначаются shortcut от Num 1 до Num 9 слева направо.
