### ISSUE TITLE
Footer in retailsalesreceipt-payments

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#176]
Добавить футер и тотал по суммам в табчасти оплаты.

**Comment by Teomit** [comment]
Для Payments добавлен footer, где есть итоги по Amount и Commission.
Ниже табличных частей есть Total, который должен выводить итоги по Item list.

**Comment by bryaleks** [comment]
В задаче речь идет только о футере в таблице оплат. Секция общих итогов документа это тема отдельной задачи
