### ISSUE TITLE
Boxing

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1767]
1. На форме SC сделать признак (true/false) SaveScannedBarcode. Если галочка стоит, записывать просканированые шк в регистр T1010S_ScannedBarcode. Важна дата/время/очередь сканирования.
2. Печать этикеток WB. Сделать обработку, куда можно скармливать документы (SC/SI остальные потом) и откуда можно печатать этикетки.
3. Добавить в SC 3 реквизита: isPackage (Boolean), PackageID (String 25) = "SC"+Number, ExternalPackageID (String 25).

**Comment by DementorAK** [comment]
Пункты 1 и 3 в пулле 1769.
Пункт 2 будет в расширении ИМ.
