### ISSUE TITLE
Consequent discounts

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#1774]
У нас не совсем корректно работает порядок применения суммовых скидок. у скидки Скидка на тип цен стоит  Приоритет 1, а в Ручной скидки на документ 5. Но распеределение суммы ручной скидки производится в соответствии с первоначальной ценой, которая была до применения Скидки на тип цен. Сейчас из-за этого со старой программой не совпадают суммы скидок в разрезе товаров. Применение суммы скидки с приоритетом 5 должно производиться в соответствии с построчными суммами, которые получились после применения скидки с приоритетом 1. Сейчас общая сумма скидки верная, но в разрезе товаров - неверная, т.к. коэффициент распределения рассчитывается по первоначальной цене. Если же скидки "засунуть" в группу Последовательное применение, то суммовая скидка на документ вообще перестает работать, а работает только процентная скидка. Также Ручная скидка на строку работает только в процентном варианте, а в суммовом не работает.

![image](https://user-images.githubusercontent.com/68659714/223129303-de141c85-86b2-4396-9726-d5ddbde6e3b6.png)

**Comment by Severnity** [comment]
@gagmaz сумовая скидка в фиксированном размере предоставляется или кассир/менеджер магазина её самостоятельно могут регулировать?

**Comment by Severnity** [comment]
необходимо обновить обработку Document discount
