### ISSUE TITLE
Add to scan barcode form Serials

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1775]
- [x] В обработку сканирования надо добавить серии.
- [x] Добавить их в табличку, разместить под товаром
- [x] При нажатии Done - переносить их в документ. Аналогично при открытии формы - тоже данные тянутся из документа.
- [x] Добавить галочку Скрыть оформление. Если открывается форма с пустыми данными, т.е. в документе пусто - галочку ставить автоматом, если данные какие то передаются из документа - галочку оставлять снятой.
- [x] Немного раздвинуть кнопки +1 и поиска штрихкода, а то они прям слитно идут на новых версиях.
- [x] Если сканируется товар с серией, но серия не указана, то открывать страничку с вводом количества, и там же вывести колоку серий, и пусть указывают. Фильтры которые надо кинуть на колонку - можно подстмотреть в обычной форме подбора серий в документе, при выборе серии.
- [x] Добавить сигналы - добавлен товар успешно, ошибка когда штрихкод не найден, информацию о том, что надо указать серию, три разных звука. Как со звуками работать можно подсмотреть в обработке MobileInvent (```MobileSubsystem.Play(Sound.Error);```)

**Comment by Severnity** [comment]
- [ ] В случае если учет по серийным номерам не ведется, то в колонке Serial lot number не должно быть надписи Empty value (товар отсканирован через мобильную форму, изначально этого товара в документе нет)
