### ISSUE TITLE
LockDataModificationReasons ItemForm

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1792]
Для удобства можно в верхней части Rules добавить перпеключатель по виду метаданных, что бы можно было отфильтровать выпадающий список у реквизита Type, удобне когда не полотно выходит из всех объектов, а например только документы.
Так же удобней было бы убирать из списка объекты, которые уже есть в списке (как в налогах)

**Comment by Severnity** [comment]
база по тегу @AccessRights
