### ISSUE TITLE
Bug with report AdditionalDocumentTablesCheck 

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#1805]
Отчет не работает по таким документам:

Document.Bundling
Document.ItemStockAdjustment
Document.PhysicalCountByLocation
Document.SalesReportFromTradeAgent
Document.SalesReportToConsignor
Document.Unbundling
![image](https://user-images.githubusercontent.com/66120736/224990236-6bc862f5-f964-46b1-a503-e83043653a73.png)

**Comment by DementorAK** [comment]
Отчет потерял актуальность и запланирован к удалению.
