### ISSUE TITLE
Create features for add atributes from extensions

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#181]
@Severnity Надо написать новые тесты на функционал.
Добавили автодобавление на форму объектов реквизитов, которые были добавлены в расширении.
Надо теперь написать тесты на это.
Логика пока такая - если расширить реквизит с именем где есть "_", то программа его автоматом нарисует на форме

**Comment by Severnity** [comment]
@DitriXNew получается мне для тестов понадобится расширение которое будет добавлять реквизиты на форму и имя добавленного реквизита должно содержать "_"?
