### ISSUE TITLE
Update features for 8.3.17+

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#183]
Надо обновить тесты, по умолчанию в системе - убрали кнопку Провести по умолчанию.
Так что все тесты на этой почве упали.
Вернул щас на 8.3.16
http://localhost:9200/repository/download/IRP_RunVA/3939:id/allure-report.zip!/index.html#behaviors/1fa8f10bfbbd67e6ecb7e57f3701bc25/5c6332c1c2ea26ea/

**Comment by Severnity** [comment]
кнопка Провести была переведена как Send. Это баг платформы, ждем исправления со стороны 1С
