### ISSUE TITLE
Import/Export object from DB

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1836]
Необходимо разработать механизм, который позволит в два клика перенести некую инфу из одной базы в другую.
Например, я настраиваю скидки в тестовой базе, и потом хочу пренести их в прод. Или у меня возникла ошибка в проде, документ там не грузится, и мне надо этот же документ воспроизвести на копии.

**Comment by DitriXNew** [comment]
Открываем нужные нам списки - документа, справочники, регистры сведений и т.д.
Открываем обработку. Жмем обновить - система смотри где в открытых формах текущий элемент выбран как таблица и считывает выделенные строки.
После этого жмем на сериализацию, и система отдает сериализованное представление этих объектов. В развернутом виде и в архивном.
![изображение](https://user-images.githubusercontent.com/11927866/228635769-b36bc892-f542-413e-af9d-d678fa09f0c6.png)

**Comment by DitriXNew** [comment]
После этого заходим в другую базу, и а вкладке Импорт вставляем эти данные:
![изображение](https://user-images.githubusercontent.com/11927866/228635992-db2506f0-c8e6-4ed9-897c-4f9af2755f27.png)

Надо учесть, что если база куда импортируются данные, находтся в статусе прод, то система данные не запишет, пока на вкладке настроек не поставят галочку, что разрешают грузить в прод

**Comment by DitriXNew** [comment]
Если они отличаются, то истема не сможет десериализовать объект, и ничего не загрузится.

**Comment by andreyvorobyov2** [comment]
Если реквизит в одной конфигурации имеет один тип, а в другой это же реквизит имеет составной тип то платформа вылетит в крит, это старый баг надо проверить, возможно уже исправлен

**Comment by andreyvorobyov2** [comment]
https://infostart.ru/1c/articles/1481155/

**Comment by DitriXNew** [comment]
> Если реквизит в одной конфигурации имеет один тип, а в другой это же реквизит имеет составной тип то платформа вылетит в крит, это старый баг надо проверить, возможно уже исправлен

Ну хз, система то никак не узнает какой там тип, крит будет только если тип другой, которого нет. Но это норм ситуация, нехер тянуть что попало :)
