### ISSUE TITLE
Payment form

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1843]
![image](https://user-images.githubusercontent.com/32883592/229275888-d5ef1524-331d-4286-987b-70fd9dba8dbd.png)

- [ ] Кнопки и список оплат не растягиваются при растягивании формы
- [x] При выборе вида оплаты по карте левая часть должна прятаться скорее всего

**Comment by DitriXNew** [comment]
Там надо учесть, что экраны могут быть и квадратные. Как вариант - надо протестировать форму через рдп например, где поставить разрешение 1280*720. Она там тоже нормально должна выглядеть

**Comment by DementorAK** [comment]
@bryaleks  Нужно так? Или еще что-то?

![Image](https://github.com/IRPTeam/IRP/assets/5967038/4edf37af-24b6-49ad-ae71-3cc2099e34e3)

**Comment by bryaleks** [comment]
@DementorAK а как открываются слева окошки по картам и платежным агентам?
