### ISSUE TITLE
Grouping when uploading from excel

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1844]
В PO/SO/ITO/SRO/PRO необходимо все таки группировать по ItemKey позиции при загрузке из экзеля
Не группировать актуально для тех документов, где есть разбивка по серийникам

Тянуть дальше цепочку линковок из заказов довольно проблематично, когда в строке 1 шт

**Comment by DitriXNew** [comment]
Теперь система проверяет, что если в документе нет серийников, то тогда игнорируется настройка AlwaysAddNewRowAfterScan при сканировании товаров.
И игнорируется настройка NotUseLineGrouping при загрузке из табличного документа.

Также пофиксил ошибки с инвентами и каунтами. Так как там по умолчанию ставилось что серийник есть, даже если галочка - учет серийников в самом документе была выключена.

По тестам надо добавить проверку в SO, SI, PhInv. CBL
Для последних двух надо протестить и сканирование и загрузку в случаях когда галочка учета по серийникам включена, а потом когда выключена. Если она выключена - строки должны группироваться.
