### ISSUE TITLE
Item + Item key presentation String 500

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1868]
![image](https://user-images.githubusercontent.com/32883592/232345162-4862e46c-6ea3-406c-a21f-4852d40e88cc.png)

**Comment by DementorAK** [comment]
@bryaleks тут нужно исправить элемент на форме только для LinkUnlinkDocumentRows или еще для каких-то форм? Похожй реквизит я нашел на EditTax, AddLinkedDocumentRows и InfoLinkedDocumentRows. Может еще где-то есть, но там они называются не RowPresentation

**Comment by bryaleks** [comment]
@DementorAK выявятся в других местах, будет другая задачка
