### ISSUE TITLE
Currency of price types

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1876]
Зафиксировали цену в USD, но реализацию надо выписывать в TL согласно законодательству.
В простой форме, данный кейс решается путем конвертации из валюты типа цен в валюту документа по курсу.

**Comment by Severnity** [comment]
Это уже работает. В документе необходимо поменять Currency 
![image](https://user-images.githubusercontent.com/66120736/235159778-116b65be-0dca-4210-a196-d9128aa7056e.png)
Источник курса для пересчета указывается в виде цены
![image](https://user-images.githubusercontent.com/66120736/235159991-53d101bf-3749-4ba3-87ff-109fefc336ee.png)
