### ISSUE TITLE
Credit note and Debit note

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#192]
Текущий документ Credit Debit note необходимо заменить на 2 документа: отдельно Credit note и отдельно Debit note
Логика работы документов:
![изображение](https://user-images.githubusercontent.com/66120736/90011873-059e4c00-dcab-11ea-873e-c935eab87ebd.png)
Поставщик или Покупатель определяется по соглашению

Регистры которые задействуются:
Register  "Expenses turnovers"
Register  "Revenues turnovers"
Register  "Accounts statement"
Register  "Reconciliation statement"
 
На регистры "Partner AR   transactions"/"Partner AP transactions" пока не обращаем внимание

**Comment by andreyvorobyov2** [comment]
А что занчит
На регистры "Partner AR transactions"/"Partner AP transactions" пока не обращаем внимание?
По ним работает заполнение таблицы транзакций, при нажатии на кнопку Fill transactions
Как транзакции заполнять?

**Comment by andreyvorobyov2** [comment]
"Поставщик или Покупатель определяется по соглашению" - зачем мне определять поставщик это или покупатель?

Поставщик или покупатель - это следствие а не причина.

Транзакции бывают Входящие и Исходящие - какие именно будут заполнены зависит от Operation type.
Operation type = Payable = Исходящие транзакции образованные документами Purchase invoice
Operation type = Receivable = Входящие транзакции образованные документами Sales invoice
Один документ использует только один Operation Type (реквизит в шапке) и взависимости от этого реквизита будут заполнены соглашения с поставщиком или с покупателем.

**Comment by Severnity** [comment]
По регистру если приход задолженности, то сумма с минусом
Если расход задолженности, то сумма с плюсом
Из документов убираем transaction type и Fill transaction
Credit note - expense type
Debit note - revenue type
