### ISSUE TITLE
Optimize additional document control

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1920]
Сейчас эта система на вход принимает только один документ, а надо сделать так, что бы она умела принимать на вход массив документов.
Изза особенностей реализации, надо понимать, что массив должен быть только одного типа, т.е. не может быть в одном массиве разные типы документов.
Надо доработать логику возврата и логику запроса, чтобы выполнялся один запрос, а не на каждый документ отдельно.
Запрос лежит в AdditionalDocumentTableControlReuse.CheckDocumentsQuery
С первого взгляда кажется что туда достатчно просто добавить ссылку на документ и настроить связи, а так же в таблицах сделать чтобы при их выгрузке была колонка Ref.

**Comment by DementorAK** [comment]
Данные AdditionalDocumentTableControlReuse.CheckDocumentsQuery используются только в AdditionalDocumentTableControl.CheckDocument(), которая вызывается только в двух местах: 
1. в подписке BeforeWrite_AdditionalTableControlDocument, куда всегда передается только одна ссылка
2. в обработке FixDocumentProblems, где проверка заполняется по табличной части, которая заполняется сразу всеми типами поддерживаемых документов, и где есть только фильтр по периоду.

@DitriXNew Нужна расшифровка этой задачи.

**Comment by DitriXNew** [comment]
@DementorAK 
Еще используется в отчете эта функция.
2. вот тут и проблема, что оно идет по каждому документу отдельно, а должно быть так - отправляю массив документов одного типа (именно одного типа), и функция мне возвращает ошибки в разрезе документов.
Потому что сейчас - эта штука работает мега долго, когда документов много. 
И если будешь ее делать сейчас , то ответвляйся от ветки access_newreg.

**Comment by DementorAK** [comment]
> Еще используется в отчете эта функция.

Увидел рассчитываемое поле Status с формулой: 
StrConcat(AdditionalDocumentTableControl.CheckDocument(Ref, &ErrorList), "")

Как именно ты предлагаешь переделать это поле, чтобы ускорить отчет? Или нужно в модуле менеджера вычислить таблицу документов, отдельно по типам выполнить проверки, а потом сформировать новую таблицу, которую вернуть в отчет как объектный источник?

**Comment by DementorAK** [comment]
>И если будешь ее делать сейчас , то ответвляйся от ветки access_newreg.
@DitriXNew не нашел эту ветку на гитхабе - она или удалена, или еще не опубликована.
