### ISSUE TITLE
RSR restriction

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1940]
![image](https://github.com/IRPTeam/IRP/assets/32883592/c3a5f250-76f3-4774-b34b-7c63b31d9825)

**Comment by DitriXNew** [comment]
В чем тут вопос?

**Comment by bryaleks** [comment]
Пусть команда разблокировать строки делает доступным к изменени ОРП во всех формах, где он есть

**Comment by bryaleks** [comment]
при добавлении нового документа вручную поле тоже не активно

**Comment by DitriXNew** [comment]
@bryaleks не понятна суть вопроса. Он блокируется только если у подразделения нет учета по кассовым сменам. При изменении подразделения - срабатывает обработчик обновления.
