### ISSUE TITLE
BankReceipt cash in transit posting

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1943]
Если указан CommissionIsSeparate в сумму R3021 падает сумма без учета комиссии

---------------------------------------------------------------------------------------
В банковской выписке 
Приход 90 (комментарий: комиссия 10)

В документе
CommissionIsSeparate = True
TotalAmount	90
Commission	10

Проводки
R3010 _CashOnHand		Приход	90	TotalAmount
R3021_CashInTransitIncoming		Расход	100 / 10	TotalAmount + Commission/Commission
R5022_Expenses				10	Commission
---------------------------------------------------------------------------------------
В банковской выписке 
Приход 100
Расход -10

В документе
CommissionIsSeparate = False
TotalAmount	100
Commission	10

R3010 _CashOnHand		Приход	100	TotalAmount
R3010 _CashOnHand		Расход	10	Commission
R3021_CashInTransitIncoming		Расход	100 / 10	TotalAmount/Commission
R5022_Expenses			Приход	10	Commission
---------------------------------------------------------------------------------------

**Comment by andreyvorobyov2** [comment]
![image](https://github.com/IRPTeam/IRP/assets/66310255/4c9e2b79-6178-41b4-b098-392767619da0)

в основной конфигурации Bank payment не является регистратором регистра Cash in transit incoming

**Comment by bryaleks** [comment]
перепутал название документов поправил на BankReceipt
