### ISSUE TITLE
AddAttributeAndProperty row input

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1952]
Не отрабатывает ввод по строке

**Comment by DitriXNew** [comment]
Не отрабатывает где?

**Comment by DementorAK** [comment]
@bryaleks очевидно, что проблема с каким-то типом метаданных, где в менеджере ошибка при подборе. Так где именно ошибка возникает?

**Comment by bryaleks** [comment]
> Не отрабатывает где?

да везде вроде

![image](https://github.com/IRPTeam/IRP/assets/32883592/967a7339-a314-4633-bc09-8ab446229e7e)

![image](https://github.com/IRPTeam/IRP/assets/32883592/7133fc25-cba1-41e4-bc10-5c83a11071c1)

**Comment by DementorAK** [comment]
@bryaleks  Начал по алфавиту проверять справочники, где есть мультиязычные наименования и мультиязычность в формах списка и выбора - пока у первых тоже не нашел подбора при вводе. Думаю, что это глобальная проблема. Поэтому немного расширяю эту задачу и сделаю отдельным пулом.
