### ISSUE TITLE
Generate gerkin and load data to base

### ISSUE THREAD

**Issue by Teomit** [IRPTeam/IRP#196]
Обработка, которая будет генерировать Gerkin файл фич, позволяющий в дальнейшем заполнять базу на основе этих данных.

**Comment by Severnity** [comment]
- [ ] ванесса не видит снипет у шага вида And I refill tabular section "SpecificationAffectPricingMD5" by:
- [ ]  при генерировании фичи для регистров возникает ошибка
![изображение](https://user-images.githubusercontent.com/66120736/90486040-0a4a8080-e141-11ea-8ba8-425000a5e315.png)

**Comment by Severnity** [comment]
@Teomit ванесса не видит снипеты по шагам вида And I refill tabular section "AvailableAttributes" by:
Из-за этого не могу прогрузить нормально айтем ки (нет наименования доп реквизитов)
![изображение](https://user-images.githubusercontent.com/66120736/92244764-01410980-eecc-11ea-9c8f-6b90ea8b51f6.png)

**Comment by Severnity** [comment]
при создании фичи для загрузки Partner term возникает ошибка
![изображение](https://user-images.githubusercontent.com/66120736/92437968-9e43c100-f1b0-11ea-88cd-c79cf8e442ae.png)

**Comment by Severnity** [comment]
нужно добавить галочки Select All и Unselect All (чтобы можно было выбрать все объекты, а также отменить выбор объектов)
