### ISSUE TITLE
Remove from predefined 

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#1963]
Catalog_CompanyTypes

**Comment by DitriXNew** [comment]
AddAttributeAndPropertySets отсюда из предопределенных

**Comment by DementorAK** [comment]
@Severnity нужно будет исправить тесты - удалить устаревшее значение со всех проектов. 
То что у меня засветилось:
D:\GIT\IRP\CloudStorage\features\External\ImportData.feature
D:\GIT\IRP\IM\features\External\TestDataBase.feature
D:\GIT\IRP\IRP\features\External\ImportData.feature
D:\GIT\IRP\IRP\features\External\Landed cost\ImportCatalogs.feature
D:\GIT\IRP\IRP\features\External\TestDataBase.feature
D:\GIT\IRP\irp_tr_esf\features\External\TestDataBase.feature
D:\GIT\IRP\ObiFin\features\External\TestDataBase.feature
