### ISSUE TITLE
Manuel special offers

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#197]
Необходимо разделить (или как то гибко совместить, хотя не понятно как) автоматические скидки расчитываемые по условиям и ручные скидки который пользователь вводит ручками в табличной части на строку. Ручные скидки по идее должны редактироваться напрямую в табличной части товаров и "накручиваться" сверху на сумму автоматической скидки

**Comment by Severnity** [comment]
нужно детальнее расписать
