### ISSUE TITLE
Filling in Retail Sales Receipt from Point of sale

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#199]
При создании документа Retail Sales Receipt из РМК есть проблема с заполнением:

- [x] Store - не заполняется

- [x]  Business unit - не заполняется

- [x]  необходимо сделать заполнение кассы на вкладке Payment

- [x] если первый товар сканируется, а второй подбирается, то в Retail Sales Receipt по первой строке Business unit  не заполняется
![изображение](https://user-images.githubusercontent.com/66120736/92566908-986bdf80-f285-11ea-86f0-93b85926c62e.png)

**Comment by bryaleks** [comment]
BU заполнять и в шапке (= Магазин) и в строках (=кост центр)

**Comment by Severnity** [comment]
@Teomit @bryaleks у меня в версии которая в ветке дев склад и бизнес юнит не заполняется (вчерашняя сборка)

**Comment by Severnity** [comment]
также необходимо сделать заполнение кассы на вкладке Payment, сейчас заполняется только банковский счет

**Comment by Severnity** [comment]
заполнение кассы работает в базе ксиоми. Необходимо заполнять из Workstation

**Comment by Severnity** [comment]
@Teomit если заполнить кассу в Workstation, то при выборе вида оплаты в POS возникает ошибка
![изображение](https://user-images.githubusercontent.com/66120736/94343005-d145db80-001d-11eb-8d77-f6e7448d3ff6.png)
