### ISSUE TITLE
Records report

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#1995]
Лучше инвертировать галочки, что бы по умолчанию не выходили технические регистры и были только проводки по валюте транзакции, а также надо свернуть их в группе, иначе занимают часть экрана.
![image](https://github.com/IRPTeam/IRP/assets/32883592/4b8b3b1e-958a-4d30-8f7a-4695fc18bb61)

**Comment by Severnity** [comment]
@DementorAK необходимо сделать чтобы форма запоминала состояние. Галочки инвертировать не нужно
