### ISSUE TITLE
Inactive button payment with Card in the Point of sale

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#200]
В РМК кнопка оплата картой неактивна
![изображение](https://user-images.githubusercontent.com/66120736/90376462-30a7e780-e07f-11ea-9c42-5d16bde3f3a8.png)

**Comment by bryaleks** [comment]
@Severnity что бы карта была активна нужно ее указать в соглашении по банку.

**Comment by Severnity** [comment]
@bryaleks в соглашении по банку указывала, но на текущей версии в ветке дев у меня кнопка неактивна
