### ISSUE TITLE
All Codes/Number read only

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#2017]
Сделать все коды и номера документов только чтение

**Comment by Severnity** [comment]
надо чтобы была возможность для тестов эту опцию отключать

**Comment by DitriXNew** [comment]
Надо сделать механизм, который будет делить все реквизиты объекта на 3 типа:
1. Доступно изменение всегда
2. Изменение не доступно после записи, а если хочешь изменить - открывается форма, где ты даешь добро - менять их или нет. В эту форму по хорошему должен прилетать тип объекта и реквизит его, путь реквизита, путь формы и закголовок. И человек ставит галочку что он хочет это изменить. Учесть, что могут данные прилетать из таблицы.
3. Набор реквизитов, которые может менять только администратор, т.е. код/номер, автор, возможно что то еще добавится. При изменении - тоже всплывает форма, эта же, где у админов есть еще одна галочка - разблокировать ключевые реквизиты.

Главное в том, чтобы можно было потом написать проверки, например, если я хочу изменить вид товара - то система должна проверить, что по нему нету никаких движений, и тогда давать изменить. Или я хочу изменить контрагента в продаже, а по этой продаже уже есть оплата. Такие вещи можно или разблокироват с предупреждением, или вообще запрещать менять.

Накидывайте.
