### ISSUE TITLE
On return with POS set row as none code string

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#2034]
При возврате через пос, надо сделать чтобы можно было пропускать контрольные строки и возращать товар без контрольных строк

**Comment by DitriXNew** [comment]
Добавил две кнопки.
![image](https://github.com/IRPTeam/IRP/assets/11927866/2f0ab8b9-1fa8-494c-8de7-964d81fa7916)

первая кнопка указывает что это товар без контроля, т.е. даже если в самом товаре указывается дополнительный контроль, то вот эта кнопка "Approve" закрывает форму и снимает признак контроля. Соответственно - товар продается как обычный.

Вторая кнопка - отображает на форме одноименную опцию, которая сразу включается.
После этого - надо просканировать штрихкод, который завязан на серию, и из этой серии потом возьмется реквизит CodeString, и подставится в форму, пройдя все проверки, как будто его и просканировали.

**Comment by bryaleks** [comment]
Aprove without scan = Sell without code string
