### ISSUE TITLE
On double click in CRS

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#2048]
- [x] При двойном клике по чеку ккм в ОРП

Поле объекта не обнаружено (Ref)
{Document.ConsolidatedRetailSales.Form.DocumentForm.Form(62)}:OpenForm("Document.RetailSalesReceipt.ObjectForm", New Structure("Key", CurrentData.Ref));

[ScriptRuntimeError, ScriptUseError]

- [x] В форме ОРП необходимо также выводить ПКО/РКО/Перемещение денег (изъятия) и расходники, которые пробивались через фискалку. И удобно разделить суммы на приход/расход

**Comment by Severnity** [comment]
данные по пробитым документам через фискалку попадают в регистр сведений Fiscal documents
