### ISSUE TITLE
Access user

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#2058]
- [ ] Сделать замену пользователя
- [x] Проверить изменение пароля пользователя когда стоит галочка Изменить пароль при входе, если пароль не проходит сложность, то выдается ошибка и окно закрывается
- [x] Запретить закрывать окно изменения пароля при входе, если парол ьне изменен

**Comment by bryaleks** [comment]
-- стоит контроль уникальности последних паролей пользователя
Добавил нового пользователя
Установил пароль
Записал
Не закрывая форму указал партнера, при записи выходит ошибка

![image](https://github.com/IRPTeam/IRP/assets/32883592/f6a6f953-46be-4f90-a017-7570502aac48)
