### ISSUE TITLE
Info Message "Items were not received from the supplier according to the procurement method"

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#207]
При создании Shipment confirmation на основании Sales order с методом обеспечения purchase до момента получения товара от поставщика должно высвечиваться сообщение Items were not received from the supplier according to the procurement method

- [ ] 1. Пользователь создает Sales order (непрямая схема работы Shipment confirmation before Sales invoice)

2. Добавляет в него товар с методом обеспечения purchase
3. Пробует на его основании создать Shipment confirmation. Должно высветиться сообщение (Error_031) Items were not received from the supplier according to the procurement method. Сейчас высвечивается сообщение The are no lines for with you need to create a Shipment confirmation document in the Sales order document.

- [ ] 1. Пользователь создает Sales order (непрямая схема работы Shipment confirmation before Sales invoice)
2. Добавляет в него товар с методом обеспечения purchase
3. Создает документ Purchase order (товар еще не получен)
3. Пробует на  основании Sales order  создать Shipment confirmation. Должно высветиться сообщение (Error_031) Items were not received from the supplier according to the procurement method.Сейчас высвечивается сообщение The are no lines for with you need to create a Shipment confirmation document in the Sales order document.

![изображение](https://user-images.githubusercontent.com/66120736/90482738-5b0baa80-e13c-11ea-94cc-639d18a3a818.png)

Тест для проверки _015450 check message output for SO when trying to create a purchase order/SC

**Comment by DitriXNew** [comment]
@Severnity надо обновить задачу,  я не вижу ее в тестах,  и этих строк не вижу в коде ирпы.

**Comment by Severnity** [comment]
@DitriXNew задачу и тест обновила

**Comment by DitriXNew** [comment]
@Severnity  Кидай плиз в следующие разы ссылку на сам тест, причем переходя в него из гита, а не тим сити. Чтобы там было ".lastSuccessful", тогда можно будет быстро увидеть что задача выполнена, и мне искать не надо будет.
И указывай из какого тега этот тест

http://95.216.127.147:9200/repository/download/IRP_RunVA/.lastSuccessful/allure-report.zip!/index.html?branch=develop#packages/168be15c1e1a058b5e0e656293249d92/4b9936e5d7fadd84/
