### ISSUE TITLE
Wrong info message when trying create extra return

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#208]
При попытке создать Sales return или Sales return order на основании Sales invoice по которому уже все товары были возвращены должно появляться сообщение There are no products to return in the "Sales invoice" document. All products are already returned. Сейчас ошибочно появляется сообщение There are no products to return in the "Purchase invoice" document. All products are already returned.
1. Пользователь создает Sales invoice
2. На основании него создает Sales return (возвращает весь товар)
3. При попытке повторного создания Sales return или Sales return order должно высветиться сообщение которое указано выше.

Тест для проверки message when trying to create Sales returm order based on Sales invoice when all products have already been returned

**Comment by DitriXNew** [comment]
PurchaseReturn
472: ErrorMessage = StrTemplate(R().Error_021, Metadata.Documents.PurchaseInvoice.Synonym);  

PurchaseReturnOrder
310: ErrorMessage = StrTemplate(R().Error_021, Metadata.Documents.PurchaseInvoice.Synonym);  

RetailReturnReceipt
421: ErrorMessage = StrTemplate(R().Error_021, Metadata.Documents.RetailSalesReceipt.Synonym);  

SalesReturn
537: ErrorMessage = StrTemplate(R().Error_021, Metadata.Documents.SalesInvoice.Synonym);  

SalesReturnOrder
313: ErrorMessage = StrTemplate(R().Error_021, Metadata.Documents.SalesInvoice.Synonym);  


Удалил дубли строк, заменил на одну и ту же. Напишите если где заменил не правильное основание
