### ISSUE TITLE
Commission trading changes

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#2093]
Изменения по комиссионной торговле:
1. комиссионер указывается в реквизите Item и/или item key. 
2. регистр InformationRegister.ConsignorSerialLotNumbers больше не используется
3. при добавлении комиссионного товара в документ в котором есть inventory origin и используется комиссионная торговля комиссионер проставляется из номенклатуры. Приоритет из item key, если не заполнено то смотрим на Item, если не заполнено в Item, то это собственный товар. Под добавлением номенклатуры подразумевается сканирование, выбор из списка, ввод по строке, выбор через формы подбора или при вводе на основании
4. партии комиссионного товара рассчитываются пост фактум по логике по которой работает расчет себестоимости
Если по номенклатуре будет несколько комиссионеров, то это разные номенклатуры или разные item key
5. продумать кейс когда комиссионый товар был продан до момента перехода на IRP и теперь этот товар возвращают
6. запретить проводить PI в случае если указанный партнер отличается от того который указан в номенклатуре или в item key если это получение комиссионного товара

**Comment by bryaleks** [comment]
+ Добавить справочник ConsignorKey, в котором будет 2 реквизита Company, Consignor. В Item/ItemKey указывать этот справочник, что бы было понятно для какой организации это комисиионный товар.
+ Контроль в поступлении, что бы нельзя было принять на комиссию, не комиссионный товар данного партнера.
