### ISSUE TITLE
Tax changes

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#2094]
В документах необходимо добавить фиксированный налог VAT.
Текущий механизм по налогам с табличной частью будет использоваться только для акцизов, налога на роскошь и т.п.

**Comment by DitriXNew** [comment]
В первом подходе сделать так, чтобы при записи обновлялась таблица налогов.
В налоги добавить перечисление TaxType, где будет пока только VAT и Other
При записи очищать таблице налогов и заполнять ее из таблица товаров, если тип налога НДС
Колонку для НДС не отрисовывать программно, а сделать хардкодно.
