### ISSUE TITLE
Postponed retails receipts

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#2136]
Для чеков ККМ как продажа, так и возврат необходимо реализовать возможность из "откладывать".
У нас есть два кейса, когда используются ОРП, и когда не используются.
Поэтому для реквизита в RRR/RSR нужно добавить реквизит TransactionType с перечислениями:
- Completed - отрабатывает как сейчас
- Canceled - не делает проводок
- Postponed - не делает проводок
- PostponedWithReserve - ставит товары в резерв (снимает с фри стока, ставит в сток резервешн), актуально для продажи

В рабочем месте, добавить галочку:
- PostponeWithReserve - регламентирует значение по умолчанию при откладывании чека продажи, если да - с резервом, нет - без резерва.

Если стоит галочка в рабочем месте, что используется ОРП, тогда перед закрытием смены ругаемся на отложенные чеки, и заставляем их или пробивать или анулировать. Если клиенту надо подержать в резерве товар на следующий день, надо создавать SO

В РМК добавить 3 кнопки:
PostponeReceipt
GetPostponedReceipts - открывается список отложеных чеков данного Branch
CancelReceipt

**Comment by DitriXNew** [comment]
а кнопки куда добавить то? И может ли быть отложенный возврат?

**Comment by bryaleks** [comment]
кнопки можно добавить под шестеренку.
да, возврат тоже может быть отложен или анулирован. не только резерва
