### ISSUE TITLE
Cancel bank payment

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#2209]
Нужно добавить окно запрашивающее подтверждение от пользователя "Вы точно хотите сделать возврат денег клиенту?" под кнопку "Отмена" в окне оплаты при проведении возврата день в день

**Comment by bryaleks** [comment]
И еще написать, что операция не может быть анулирована и не вопрос "да/нет", а лучше галочкой "Я, понимаю что операция ВОЗВРАТА денег клиенту НЕ МОЖЕТ быть анулирована"
