### ISSUE TITLE
DebitCreditNote

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#2226]
Нужен документ, который позволит перекидывать задолженность с одного партнера/контрагента/соглашения/инвойса на другого, это может быть как покупатели так и поставщики.
При текущем функционале надо создавать отдельно Дебит отдельно Кредит ноты и прогонять через PL Регистры.

Кейс 1: Партнер А/Контрагент А и Партнер Б/Контрагент Б хотят между собой перекинуть задолженности. Это могут быть как покупатель/покупатель, так и поставщик/покупатель (перекидывать AP/AR)
Кейс 2: Реализация была по бранчу А, а заплатили на счет бранча Б и надо перекинуть задолженость.
Кейс 3:

**Comment by DitriXNew** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/52hQWDt7/3-test)
