### ISSUE TITLE
Autofilling expense types in PI

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#2275]
В PI заполняется статья затрат, не смотря на то, что она указанна на другую характеристику
![image](https://github.com/IRPTeam/IRP/assets/32883592/cdb07370-a732-4bc0-a8eb-59bb5ccfa5c2)

**Comment by Severnity** [comment]
срабатывает автоподстановка статьи затрат от предыдущей строки

**Comment by Severnity** [comment]
https://bilistteam.atlassian.net/browse/IRP-67
