### ISSUE TITLE
Mechanism for correcting document movements

### ISSUE THREAD

**Issue by mybracho** [IRPTeam/IRP#2424]
Создать механизм, который позволит править движения документа вручную. При этом, документ должен получить признак "Есть ручные исправления в движениях". При наличии этого признака, пользователь должен получить информацию, при открытии документа, что при его перепроведении ручные правки удалятся.

**Comment by DitriXNew** [comment]
Надо сделать кнопку - Отредактировать движения вручную. Это может быть команда общая.
При нажатии - открывается форма редактирования.
В ней есть галочка - Ручные проводки.
Так же страницы с таблицами движений.
Таблицы показывают текущие движения.
Пока не поставить галочку - Ручные проводки - таблицы редактировать нельзя.
После установки галочки - редактируем таблицы и жмём Записать.
В документе есть общий реквизит - Ручные проводки. Он ставится в истину и записываются проводки и та галочка в документ. В транзакции.

Кроме этого - надо предусмотреть, что если при проведении проводки не  отличаются от того что в регистр ляжет и галочка стоит - то выдавать сообщение, что Ручные проводки можно снимать.
Если отличия есть - выдавать ошибку и блокировать поведение.

В форме редактора проводок - сделать кнопку - Анализ проводок. При ее нажатии - система должна написать - в каких регистрах отличия. Ее же выполнять при открытиии формы.

Сделать проверки на то, что можно менять только проведенный.
Запретить отменять проведение документа с ручной корректировкой.

В страницах таблиц вывести в заголовках количество строк в таблице.
Сделать две икноки - галочка и карандашь. Ечли движения отличаются - то ставить карандашь, если нет - галочку. Обновляться должно при нажатии кнопки анализ, ну или при редактировании таблицы.

Поправить отчет Алализа движений документов. Если есть галочка Ручные проводки, то тогда под регистром рисовать текущие проводки и там же - проводки которые были бы, если бы галочки не стояли. Различать их так - не ручные проводки перечеркивать текст. 
Также определять колонку в которой есть отличия между ними и разукрасить ее в зеленый фон. 
Обратить внимание, что проводок может юыть больше, чем ручных, или вообще не быть и наоборот.

**Comment by mybracho** [comment]
- [ ] 1. Вывести строку под строкой. Что было и что будет
- [ ] 2. Через запятую в новом столбце вывести названия колонок которые редактировались
- [ ] 3. Добавить флаг, который скрывает технические колонки в ядре
- [ ] 4. Перехватить форму отчета в расширении UNIT и для п.3 добавить оторбаржение технических колонок
- [ ] 5. В случае если были изменения около названия регистра выводить об этом информацию
