### ISSUE TITLE
ExpenseRevenueAccruals

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#2459]
Новые документы: 
ExpenseAccruals
RevenueAccruals

ВидОперации: Accrual/Void/Reverse, если сторно или обратная проводка, то обязательно выбрать Basis (для информации, что ты сторнируешь), основанием является accruals у которого вид операции Accruals.
Новое перечисление:
AccrualsTransactionType: Accrual/Void/Reverse (между Void и Reverse разница в том, что Void делает сторнирование, а Reverse обратную проводку, то есть меняет местами Приход/Расход, так как не всегда сторнирование это хорошо)

Новые перечисления
OtherPeriodExpenseType: ItemsCost/ExpenseAccruals
OtherPeriodRevenueType: ItemsRevenue/RevenueAccruals

В PI/SI в ItemList пометить IsAdditionalItemCost как DELETE_IsAdditionalItemCost и рядом добавить перечисление (на форме очищение добавить не забыть надо), в проводках если заполненно перечисление кидать проводки в регистры R6070T_OtherPeriodsExpenses/R6080T_OtherPeriodsRevenues добавив туда измерение по добавленному перечислению.

В документах AdditionalCostAllocation и AdditionalRevenueAllocation при подборе данных (есть формы подбора, в них запросы) поставить отбор по OtherPeriodExpenseType.ItemsCost//OtherPeriodRevenueType.ItemsRevenue

Соответственно в документах ExpenseAccruals и RevenueAccruals отборы стоят по OtherPeriodExpenseType.ExpenseAccruals//OtherPeriodRevenueType.RevenueAccruals

1 кейс: поставщик выставляет каждый месяц 100 USD, но инвойсы доходят через несколько дней, а месяц закрывают 2 числа. Бухгалтера начисляют Accruals на 100 USD по курсу 30, отражая тем самым затраты в текущем месяце и закрывается это неким промежуточным счетом ХХ (? аналитика).
По МСФО в начале следующего месяца такие начисления Accruals сторнируется и все возвращается на свои места. Когда партнер доносит инвойс он делает обычные проводки.
Если не донес в текущем месяце, операция повторяется снова.

ВидОперации: Начисление и Сторно

2 кейс: поставщик выставил 10.000 USD за 10 месячное обслуживание и по учетной политике или по МСФО такие услуги должны быть отражены в течении 10 месяцев, а ндс принят сейчас в зачет.
Бухгалтер вводит PI и указывает что это услуги других периодов (похоже на наш механизм учета доп расходов на товары) сумма кидается на промежуточный счет ХХ (? аналитика)
Замет создает 10 документов на каждый месяц, которые по 1.000 USD забирают суммы с счета ХХ и кидают на затраты.

-- по обоим кейсам зеркальная логика применима как к закупкам, так и к продажам (например отели обязаны отчитываться о прибыли за каждый день пребывания постояльца, но инвойс и НДС выписывать в конце (или когда захотят)). То есть, и акруалсы и доходы будущих периодов работают в обе стороны.

ERA ExpenseRevenueAccruals - документ, который отражает доходы/расходы других периодов. Сможем ли мы закрыть оба фукнционала этим документом и регистрами R6070T_OtherPeriodsExpenses и R6080T_OtherPeriodsRevenues

То есть,
в 1 кейсе:
31.01.2024 ERA/ExpenseAccrual (+ R5022T_Expenses - R6070T_OtherPeriodsExpenses) 1000 USD
01.02.2024 ERA/ExpenseVoid (- R5022T_Expenses + R6070T_OtherPeriodsExpenses) 1000 USD

05.02.2024 PI + R5022T_Expenses 1005 USD

в 2 кейсе:
31.01.2024 PI + R6070T_OtherPeriodsExpenses 10.000 USD

28.02.2024 ERA/ExpenseAccrual (+ R5022T_Expenses - R6070T_OtherPeriodsExpenses) 1000 USD
31.03.2024 ERA/ExpenseAccrual (+ R5022T_Expenses - R6070T_OtherPeriodsExpenses) 1000 USD
...
30.11.2024 ERA/ExpenseAccrual (+ R5022T_Expenses - R6070T_OtherPeriodsExpenses) 1000 USD

и зеркально ERA/RevenueAccrual и SI c R6080T_OtherPeriodsRevenues

**Comment by mybracho** [comment]
Если заполнено основание, то берем курсы из документа основания при любом виде движения
Если основание не заполнено, то по типовому механизма на дату документа.

**Comment by mybracho** [comment]
EXPENCE ACCRUALS
Регистр R6070

PI Приход 1

Accrual
Вид движения Расход
Кф.Суммы 1


Void
Вид движения Расход
Кф.Суммы  -1



Reverse
Вид движения Приход
Кф.Суммы  1
