### ISSUE TITLE
Price types include tax or not

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#247]
Предлагаю в типах цен добавить признак "IncludeTax". Что бы четко понимать что цена включает НДС или нет.
Так же есть галочка в соглашении "PriceİncludeTax", которая должна регламентировать как подставить цену в документ.

то есть, если цена с ндс установлена как 110, а в соглашении указано что без ндс тогда цена в документ подставляетяс как 100, если в соглашении указано что с НДС тогда цена в документ подставляется как 110.

**Comment by DitriXNew** [comment]
#669
