### ISSUE TITLE
Sales return based on sales reciept

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#263]
Надо переносить таблицу оплат и retailcustomer в документ возврата из реализации

**Comment by DitriXNew** [comment]
Надо предусмотреть, что один возврат = строго одной реализации, т.е. не может быть что на две реализации один возврат. Наоборот - может быть.

**Comment by DitriXNew** [comment]
Оплаты как есть - так и переносить.

**Comment by bryaleks** [comment]
это только когда ввод на основании, в режиме РМК надо будет оплаты подвязывать как в продаже. но это другая задачка
