### ISSUE TITLE
In POS when change price - CurrentPriceType change too

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#264]
Если изменить строку в POS, то сбивается вид цен и после этого, в любой новой строке и штрихкоде - нет цены

**Comment by bryaleks** [comment]
такакя же ситуация была при добавлении товаров через ШК в SI.

**Comment by Severnity** [comment]
у меня после обновления цена в POS если очистить цену по предыдущему товару не подставляется
То есть добавляю первый товар
Добавляю второй товар и меняю по нему цену вручную
Добавляю 3 товар через подбор - цена автоматически не заполняется
Добавляю 4-й товар через поиск по штрих-коду - цена автоматически не заполняется

![изображение](https://user-images.githubusercontent.com/66120736/92442468-9daf2880-f1b8-11ea-981a-85c922709a0d.png)
