### ISSUE TITLE
Duplicated posting in register Order procurement (procurement method - purchase)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#27]
1. Пользователь создает Sales order с двумя одинаковыми товарами в разных строках (метод обеспечения - purchase)
![image](https://user-images.githubusercontent.com/66120736/84135148-46cb7300-aa52-11ea-993d-f76637886c81.png)

2. На основании Sales order создает 2 заказа поставщику (в одном - первая строка, во втором - 
вторая строка). 
![image](https://user-images.githubusercontent.com/66120736/84135230-6793c880-aa52-11ea-92a7-767351ac47b6.png)
![image](https://user-images.githubusercontent.com/66120736/84135261-6ebad680-aa52-11ea-845f-60e4c319cd1f.png)
По второму Purchase order задваивается движение по строке на 15 штук которой в нём нет.
![image](https://user-images.githubusercontent.com/66120736/84136315-ca399400-aa53-11ea-80ae-3b514eabfdd4.png)

Второй вариант бага: 
если при создании Purchase order удалить первую строку (оставить строку на 15 штук) то возникнет вот такая ситуация
![image](https://user-images.githubusercontent.com/66120736/84137326-37015e00-aa55-11ea-8934-9331f19fd53a.png)
![image](https://user-images.githubusercontent.com/66120736/84136741-6499d780-aa54-11ea-8e1b-a77e8d947785.png)

**Comment by andreyvorobyov2** [comment]
Сдклал все тоже самое, воспроизвести не удалось, никаких лишних движений нет, нужна DT-шка с воспроизведенным багом. 
![image](https://user-images.githubusercontent.com/66310255/84523564-2a913580-ace1-11ea-91c3-16271dc69e2f.png)
