### ISSUE TITLE
Filling in Business unit in the Retail Sales receipt 

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#287]
В Retail Sales receipt при добавлении товара путем поиска по штрих-коду либо же из формы подбора товара перестал заполняться Business unit
![изображение](https://user-images.githubusercontent.com/66120736/93558695-a9ec7000-f986-11ea-98ba-d4a9b4be623e.png)
При добавлении товара через кнопку Add бизнес юнит заполняется

Также из-за того что не заполняется Business unit Retail Sales receipt не проводится при создании из формы POS
![изображение](https://user-images.githubusercontent.com/66120736/93558916-27b07b80-f987-11ea-857b-cf6f5fad9d54.png)

**Comment by Severnity** [comment]
@Teomit в Retail sales receipt бизнес юнит необходимо будет вынести в шапку и заполнять его из настроек пользователя

**Comment by Teomit** [comment]
> 
> 
> @Teomit в Retail sales receipt бизнес юнит необходимо будет вынести в шапку и заполнять его из настроек пользователя

Уже был кем-то вынесен. Заполняется нормально.
В табличной части у реквизита убран признак обязательного заполнения. Удаляем поностью реквизит из табличной части?

**Comment by bryaleks** [comment]
@Teomit не надо его удалять. Он будет использоваться для проводок по ревенью регистрам.

**Comment by Severnity** [comment]
@Teomit в табличной части необходимо поправить заполнение бизнес юнита из пользовательских настроек: чтобы заполнялся при добавлении товара путем сканирования либо же из формы подбора.
При изменении бизнес юнита в шапке, в табличной части бизнес юнит перезаполняться не должен

**Comment by Severnity** [comment]
также нужно добавить в табличную часть колонки Revenue type и Additional analytic ( по аналогии с оптовыми документами)
