### ISSUE TITLE
DontCalculateRow in Purchase invoice

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#308]
В документе Purchase order добавить флаг DontCalculateRow. При значении Истина у флага не будет отрабатывать пересчет по строке, но будет отрабатывать пересчет по сумме документа. Также когда установлен  этот флаг, поле NetAmount будет тоже доступно для редактирования.

**Comment by Severnity** [comment]
также для остальных доков в которых есть налог и цена

**Comment by Severnity** [comment]
реализовано в документах: 
Sales order
Sales invoice
Sales return order
Sales return
Purchase order
Purchase invoice
Purchase return order
Purchase return
Retail sales receipt
Retail return receipt
