### ISSUE TITLE
Accounting module concept

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#315]
Необходимо описать концепт бухгалтерского модуля для его дальнейшего обсуждения

**Comment by bryaleks** [comment]
https://us02web.zoom.us/rec/share/3KmejlQEAPrX9MlypsXUD0WP-4ws4w1gyKcjyjhZgslMUjIxFuvGPNVJ4JOha6IJ.RSFLblLKAE4_8CQX?startTime=1601381395000
