### ISSUE TITLE
Deletion of Payee/Payer field from bank/cash documents

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#32]
Из банковских/кассовых документов необходимо удалить из шапки поле Payee/Payer. Также нужно отключить автозаполнение Payee/Payer при добавлении следующей строки (например, пользователь добавляет первую строку по Company Ferron BP, при добавлении второй строки Company Ferron BP автоматически подставляться не должно). 
![image](https://user-images.githubusercontent.com/66120736/84622837-a3151380-aee6-11ea-8bf9-7e272cab64ec.png)

**Comment by DitriXTemp** [comment]
@Teomit I fix it.
