### ISSUE TITLE
When copy add atribute row in sets - clear isConditionSet, or copy it

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#323]
Ошибка возникает, есть копировать сроку в атрибут сете, и менять там сам атрибут, то условия - не копируются.
Или надо их копировать, или очищать IsConditionSet

**Comment by DitriXNew** [comment]
Ошибка возникает при открытии любой карточки товара.

**Comment by Severnity** [comment]
реализовано копирование IsConditionSet
