### ISSUE TITLE
Forbid changes of GR/SC when they used in PI/SI

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#327]
Если GR или SC уже использованы в проведенных PI или SI то нельзя разрешать их изменять.

**Comment by Severnity** [comment]
Ситуация: 
1. на основании Sales order создают Shipment confirmation а потом Sales invoice
2. заходят в Shipment confirmation и добавляют ещё одну строку
@bryaleks надо ли запрещать такие ситуации? по сути могут забыть и потом инвойс не выписать

**Comment by bryaleks** [comment]
@Severnity я думаю что все таки надо запрещать.
Раз у нас инвойс закрывает полностью SC на основании заказа, то по идее не надо давать возможность его менять. И всегда можно еще один SC создать если пришел какой то товар или если что то забыли отправить. Ну а лучше наверное сделать это гибко и настраеваемо для пользователя (но только по разрешательной логике, то есть в настройках пользователя сделать галочку "Разрешать редактирование SC при введеном инвойсе" и тоже самое только для GR.
