### ISSUE TITLE
GR/SC quantity control in PI/SI

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#328]
Нужно сделать проверку соответсвия количеств в самом инвойсе и в документах отгрузки.
На случай если инвойс был не проведен, а количества в документах отгрузки поменялись

**Comment by Severnity** [comment]
@andreyvorobyov2 в данном случае в сообщении должно быть указано, что Dress L/Green не хватает 18 штук. В Sales invoice 20 штук, в Shipment confirmation 19 в одной строке и 19 в другой (в общей сложности 38)
![изображение](https://user-images.githubusercontent.com/66120736/95552954-4bab2e00-0a16-11eb-83d7-e5d70e5b3465.png)
![изображение](https://user-images.githubusercontent.com/66120736/95552972-536ad280-0a16-11eb-8c4a-f3a17e753ad7.png)

**Comment by Severnity** [comment]
также есть проблема когда отгружается в разных единицах измерения. В данном случае и в Sales order и в Sales invoice по Boots/S-8 74 штуки, но sales invoice провести не дает
![изображение](https://user-images.githubusercontent.com/66120736/95553450-4d292600-0a17-11eb-9306-72c2b9f7caac.png)
![изображение](https://user-images.githubusercontent.com/66120736/95553472-54503400-0a17-11eb-961e-5b919e4e9b30.png)

**Comment by Severnity** [comment]
также есть проблема, когда я удалила строку и добавила новую
Удаляю строку Dress L/Green 
Добавляю строку  Dress L/Green 
![изображение](https://user-images.githubusercontent.com/66120736/95556720-6680a100-0a1c-11eb-9ff2-cf2e6876f9fc.png)
![изображение](https://user-images.githubusercontent.com/66120736/95556734-6c768200-0a1c-11eb-942d-958279cebe0a.png)

**Comment by Severnity** [comment]
не получается провести Goods receipt с дополнительной строкой без документа основания (создан на основании PI). Кейс - поставщик прислал товар который не указан в инвойсе
![изображение](https://user-images.githubusercontent.com/66120736/95579890-123ae880-0a3f-11eb-95f0-0d1121c91525.png)
