### ISSUE TITLE
Bug when adding an items to documents in which the Item/Box switch used to be

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#33]
При добавлении товара в документы в которых ранее был переключатель Item/Box появляется ошибка:
![image](https://user-images.githubusercontent.com/66120736/84653846-d1124c00-af16-11ea-9f73-25a16f6ed2ad.png)

Перечень документов: 
Purchase order
Purchase invoice
Inventory transfer order
Inventory transfer
Purchase return
Purchase return order
Shipment confirmation
Goods receipt
PhysicalInventory
PhysicalCountByLocation
StockAdjustmentAsSurplus
StockAdjustmentAsWriteOff
Также возникает ошибка в прайс листе
![image](https://user-images.githubusercontent.com/66120736/84654819-81348480-af18-11ea-887f-4b80162d23c3.png)

**Comment by andreyvorobyov2** [comment]
Boxing, Unboxing - удалены по задаче #26 Переключатель InputType переключал между Item и Box, сейчас этого переключателя нет

**Comment by DitriXNew** [comment]
Я щас исправлю эти ошибки, а то мне горят уже

**Comment by DitriXNew** [comment]
То что нашел я поудалял, но глубоко не вникал, так что @andreyvorobyov2 ты всеравно посмотри внимательно своим взглядом, так как я удалял, конфликтов не должно быть.
