### ISSUE TITLE
No access to documents in subsystems 

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#332]
При предоставлении доступа к подсистемам и документам через Access system документы не отражаются в подсистемах, хотя через Все функции доступ к документам имеется

**Comment by DitriXNew** [comment]
Ошибку исправил, должно все появится, обрати внимание на то, что есть кнопки, которые ведут не на список документа, а на его создание, в таком случае, если прав на создание нет, то они будут скрыты
