### ISSUE TITLE
BU and Company filter problem in reports

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#335]
Не формируются отчеты под пользователем, у которого установлен фильтр по BU и Company :
AP-R01 Sales - {(3, 1)}: Поле не найдено "BusinessUnit" <<?>>BusinessUnit IN (&AccRoles_BU)
AP-R02 Purchases -  {(3, 1)}: Поле не найдено "BusinessUnit" <<?>>BusinessUnit IN (&AccRoles_BU)
SR-R02 Daily cash -  {(3, 1)}: Поле не найдено "BusinessUnit" <<?>>BusinessUnit IN (&AccRoles_BU)
SR-R03 Stock balance -  {(2, 1)}: Поле не найдено "Company" <<?>>Company IN (&AccRoles_Company)

**Comment by DitriXNew** [comment]
@gagmaz ошибку из журнала регистарции надо увидеть, так как похоже что этих реквзитов где то нету
