### ISSUE TITLE
Manufacturing

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#372]
Необходимо подготовить концепт модуля производства

**Comment by bryaleks** [comment]
-+ Bill of materials (справочник).
В шапке: Item, ItemKey, Quantity, Unit. ТабЧасти: Состав (из чего состоит товар:сырье, полуфабрикаты (semi-products), работы (отдельный вид номенклатуры - works с себестоимостью по типу цен)) и Табчасть этапы производства (ProductionStages): где указываются этапы производства, которые будут переноситься в одноименную ТабЧасть в документе производства и где можно будет галочками проставлять что выполнен тот или иной этап (а лучше что бы это был регистра отдельный).

+ Production planning
В шапке указываеься BU и период планирования (гибкий справочник с указанием даты нач и даты оконч). В строках табличной части вводится Item/ItemKeys товаров, которые планируем произвести и их спецификации + колво + едизм.
Данным документом будет отражаться план по производству готовой продукции и плановая потребность в сырье (цикл будет спускаться до самого "низа" сырьевой потребности полуфабрикатов). ! Полуфабрикат который можно купить - материал.

+ Internal supply request
Текущий документ, которым будет вводится что и когда точно нужно обеспечить.

+++ Обработка заполнения Internal supply request
Берется во внимание потребности в сырье созданные ProductionPlanning и текущие или "будущие" (то есть уже заказанные) остатки сырья и полуфабрикатов (это будет отдельная обработка анализа и заполнения данного документа).

+++ Обоботка анализа и создания Purchase order
На основании данных которые введены документом Internal supply request и данных по ценам номенклатуры партнеров будет подсказывать оператору какому поставщику выгодней дать заказ. Номенкатура партнера.

+ Production
Этим документом мы вводим фактический итог производства. Выбираем произведенный продукт и его колво. Так же должны менять фактический состав сырья, если он поменялся во время производства. Делать списание сырья и оприходование полуфабрикатов, затем списания сырья и полуфабрикатов и оприходование готовой продукции (очередность важна, для последующего расчета себестоимости).
Так же в документе будет 2 таб части: доп расходы (DirectCost) и этапы производства (ProductionStages).

+ ProductionPlanningCorrection (корректировка планирования производство)
В случае когда надо скорректировать производственный план, вводится данный документ. У него должны быть статусы. Потому что изменения в ПП нужно одобрять и исходя из изменений корректировать планы поступления сырья.
