### ISSUE TITLE
stock movements of services in all documents

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#389]
возврат не должен ложить обратно на склад услуги

**Comment by DitriXNew** [comment]
@seramiti эту задачу разве не сделал @andreyvorobyov2 ?

**Comment by bryaleks** [comment]
@DitriXNew у тебя вроде гит под рукой, зачем плодить вопросы.
https://github.com/IRPTeam/IRP/blob/44deba87c897a33df77a5ea21548c09ad09e6401/IRP/src/Documents/RetailReturnReceipt/ManagerModule.bsl#L96

**Comment by DitriXNew** [comment]
@bryaleks надо составить список регистров, по которым не должны услуги делать движения.
GoodsInTransitIncoming
GoodsInTransitOutgoing
GoodsReceiptSchedule
InventoryBalance
ItemsInStores
OrderReservation
ShipmentConfirmationSchedule
ShipmentOrders
StockAdjustmentAsSurplus
StockAdjustmentAsWriteOff
StockBalance
StockReservation

Кроме этого - услуги не должны выбираться в документах ордеров.

**Comment by DitriXNew** [comment]
@Severnity убрал фильтр на сервисы в возвратах, теперь их можно выбрать там.
И убрал проводки в регистрах складских на ретейл возрат, обычный возврат и на возврат поставщику

**Comment by DitriXNew** [comment]
@Severnity в следующий раз скидывай лучше ссылку сразу на тест
http://95.216.127.147:9200/repository/download/IRP_RunVA/.lastSuccessful/allure-report.zip!/index.html?branch=develop#packages/168be15c1e1a058b5e0e656293249d92/4b9936e5d7fadd84/
