### ISSUE TITLE
Payment by card in POS

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#406]
В POS недоступна оплата картой. Bank term заполнен
![изображение](https://user-images.githubusercontent.com/66120736/95714327-bce61d80-0c70-11eb-8172-719715ad3ba2.png)
![изображение](https://user-images.githubusercontent.com/66120736/95714361-c96a7600-0c70-11eb-9849-785bb9870a9d.png)
![изображение](https://user-images.githubusercontent.com/66120736/95714402-d6876500-0c70-11eb-9fe8-cb23de5cfa05.png)
![изображение](https://user-images.githubusercontent.com/66120736/95714454-ec952580-0c70-11eb-9d4f-c7fc3f5e0196.png)

**Comment by DitriXNew** [comment]
@Teomit я не смог вкурить логику, тебе тут быстрее разобраться, вроде все типо правильно, а оно не видит виды оплат.

**Comment by Teomit** [comment]
@DitriXNew Не видит, так как данные берутся из Business Unit (точнее с соглашения с банком). Business Unit не заполняется по умолчанию, так как теперь это общий реквизит. Необходимо в механизме сохранения настроек добавить поддержку общих реквизитов.

**Comment by Teomit** [comment]
Исправлено в рамках #423 .
