### ISSUE TITLE
Opponent -> Other

### ISSUE THREAD

**Issue by EDV-Lotse** [IRPTeam/IRP#42]
Предлагаю в каталоге Companies признак Opponent переименовать в Other и использовать для обозначения таких контрагентов, которые пока не являются ни  клиентами, ни поставщиками.
Обоснование:
подобный реквизит есть в типовых, например 1C:DRIVE, да и в Business Suite потенциальный клиент заносится в отдельную категорию как Interessent.

**Comment by DitriXNew** [comment]
Этот реквизит используется для отборов в разных формах.
А категории - делаются все таки сегментами.
Конкретно это значение Opponent - не используется сейчас нигде, и партнеры с этим признаком - не получится выбрать ни как поставщик, ни как клиент.
Мы думали просто это значение удалить и оставить остальные, пока не повесим логику.

Изначально, идея была в том, чтобы таким образом маркировать конкурентов, и грузить от них цены для анализа, и при этои, чтобы сотрудник не мог продать конкуренту ничего, или купить у него ничего, если там явно не стоит признак, что он поставщик или клиент.
