### ISSUE TITLE
Aging

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#420]
Необходимо реализовать механизм графиков оплат:
1. в соглашении указывается количество дней отсрочки платежа (работает только в случае взаиморасчетов по документам)
2. в документе реализации (Sales invoice) указывается дата оплаты (дата реализации + количество дней из соглашения). Табличная часть оплат (пользователь может её редактировать)
Дата сумма
Меняется дата инвойса, меняется дата оплаты с вопросом

**Comment by bryaleks** [comment]
[Uploading Aging report.zip…]()

**Comment by bryaleks** [comment]
[Aging report.zip](https://github.com/IRPTeam/IRP/files/5391918/Aging.report.zip)

**Comment by bryaleks** [comment]
так же из отчета надо понимать что есть не разнесенные суммы. то есть еще нужно добавить сумму аванса/переплаты
