### ISSUE TITLE
Correction document

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#429]
Необходим документ корректировки который позволит:
1. закрывать разницу между инвойсами и реализацией (например когда поставщик прислал товар которого в инвойсе нет, прямая схема работы)
2. закрывать разницу между заказами, инвойсами и GR и SC (отличие по количеству и по сумме в 0,01)

**Comment by bryaleks** [comment]
вторая часть закрывается документов SOC
про первую часть надо подумать
