### ISSUE TITLE
Error when open SI (role Full access only read)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#451]
При открытии Sales invoice под пользователем с ролью только чтение возникает ошибка
![изображение](https://user-images.githubusercontent.com/66120736/96363754-cbd04280-113e-11eb-90c6-0a758e181e22.png)

**Comment by DitriXNew** [comment]
@Severnity  ссылочку на тест бы :)

**Comment by Severnity** [comment]
@DitriXNew https://github.com/IRPTeam/IRP/blob/develop/features/Internal_new/_9500AccessRights/_9500FullAccessOnlyRead.feature
Scenario: 950041 check role Full access only read (Sales invoice)
