### ISSUE TITLE
Slider slowly loading

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#453]
При открытии номенклатуры очень много времени тратится на открытие слайдера. Хотя в большинстве случаев номенклатура открывается не для того что бы посмотреть большую картинку товара.
Необходимо сделать так, что бы по умолчанию открывался слайдер только с превью, а уже когда надо посмотреть большую картинку секциюс большой картинкой открывать по нажатию кнопки. Это применимо как с форме объекта, так и форме списка.

**Comment by DitriXNew** [comment]
Добавил параметр в функцию 
```
PicturesInfoForSlider(ItemRef, UUID, FileRef = Undefined, UseFullSizePhoto = False)
```
Т.е. если параметр передать последний ТРУ - то вернутся полноразмерная картинка
