### ISSUE TITLE
Quantity in base units

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#461]
В Unit необходимо добавить реквизит - Количество в базовых единицах
Например, 
![изображение](https://user-images.githubusercontent.com/66120736/96453814-ae28d900-1223-11eb-9458-0a9df8de58f3.png)
Если пользователь меняет значение среднего уровня, например (указывает что в упаковке 6 штук, уже не 6 штук, а 7), то количество в базовых единицах измерения должно пересчитаться для всех единиц измерения которые состояли из упаковок 6 штук.

**Comment by bryaleks** [comment]
@Severnity эта задача уже наверное не актуальна. обсудили что надо делать колво упаковок в таб частях документов
