### ISSUE TITLE
Updating agreements list when a partner segment changes

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#47]
Необходимо сделать так, чтобы перечень соглашений по партнеру обновлялся при изменении сегмента партнера без переоткрытия формы
![изображение](https://user-images.githubusercontent.com/66120736/85860347-51626800-b7c7-11ea-827a-6b03e7a2678c.png)

**Comment by DitriXNew** [comment]
Можно тестовую базу? не могу заполнить нормально все, вечно где то фигня выскакиевает какая то, и я отвлекаюсь на нее :)
@Severnity

**Comment by Severnity** [comment]
тестовая база у нас та, на которой прошли тесты. Скинуть dt?
