### ISSUE TITLE
Amount in bank payment row

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#470]
При выборе документа основания (если закрывается по документам), если сумма пустая в строке сумма должны подтягиваться из документа

**Comment by andreyvorobyov2** [comment]
Не сумма документа, а сумма долга (остатка) из регистра Partner AP transactions. И не только при выборе документа а так же при выоре соглашения, если учет взаиморасчетов ведется в разрезе соглашений (без документов)
