### ISSUE TITLE
Remaining stock control

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#472]
Необходимо добавить настройку по контролю остатков с возможностью при необходимости её отключить.

**Comment by Severnity** [comment]
+ необходимо реализовать сам контроль остатков

**Comment by Severnity** [comment]
- [ ] сформулировать первую итерацию данного функционала

**Comment by andreyvorobyov2** [comment]
R - reservation
B - balance

purchase return                R B
goods receipt                  R B
inventory transfer order       R
sales invoice                  R B
purchase return order          R
purchase invoice               R B
shipment confirmation          R B
opening entry                  R B
retail sales receipt           R B
stock adjustment as surplus    R B
sales order                    R B
retail return receipt          R B
physical inventory             R B
unbundling                     R B
stock adjustment as write off  R B
bundling                       R B
inventory transfer             R B
sales return                   R B
purchase order                 R B

**Comment by Severnity** [comment]
- [ ] при проведении Purchase invoice с ордерного склада (без заказа) возникает ошибка
![image](https://user-images.githubusercontent.com/66120736/102467608-29a6db00-4059-11eb-9928-f55f42c5b987.png)
Error running processor - 'Posting'
, reason:
{(21, 10)}: Field not found "Records.Store"
Records.<<?>>Store,
{CommonModule.PostingServer.Module(1285)}:	QueryResult = Query.Execute();
{CommonModule.PostingServer.Module(1156)}:	Return CheckBalance(Ref, Parameters, Tables, RecordType, Unposting, AddInfo);
{AccumulationRegister.StockReservation.ManagerModule(29)}:	Return PostingServer.CheckBalance_StockReservation(Ref, Tables, RecordType, Unposting, AddInfo);
{CommonModule.PostingServer.Module(1129)}:		If Not Cancel And Not AccReg.StockReservation.CheckBalance(Ref, LineNumberAndItemKeyFromItemList, 
{Document.PurchaseInvoice.ManagerModule(2788)}:	PostingServer.CheckBalance_AfterWrite(Ref, Cancel, Parameters, "Document.PurchaseInvoice.ItemList", AddInfo);
{Document.PurchaseInvoice.ManagerModule(2729)}:	CheckAfterWrite(Ref, Cancel, Parameters, AddInfo);
{CommonModule.PostingServer.Module(88)}:	Module.PostingCheckAfterWrite(DocObject.Ref, Cancel, PostingMode, Parameters, AddInfo);
{Document.PurchaseInvoice.ObjectModule(23)}:	PostingServer.Post(ThisObject, Cancel, PostingMode, ThisObject.AdditionalProperties);

, reason:
{(21, 10)}: Field not found "Records.Store"
Records.<<?>>Store,

**Comment by Severnity** [comment]
- [ ] ошибка при распроведении SO (SI и SC по нему нет)
Error running processor - 'UndoPosting'
, reason:
Object field not found (StockBalance_Exists)
{Document.SalesOrder.ManagerModule(1330)}:	StockBalance = AccumulationRegisters.StockBalance.GetLockFields(DocumentDataTables.StockBalance_Exists);
{CommonModule.UndopostingServer.Module(19)}:	LockDataSources = Module.UndopostingGetLockDataSource(DocObject.Ref, Cancel, Parameters, AddInfo);
{Document.SalesOrder.ObjectModule(41)}:	UndopostingServer.Undopost(ThisObject, Cancel, ThisObject.AdditionalProperties);
![image](https://user-images.githubusercontent.com/66120736/102473449-23682d00-4060-11eb-9b50-29a913ac1499.png)
В складке галочка Use SC
