### ISSUE TITLE
Serial numbers in POS screen

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#478]
При сканировании или подборе товара из списка, если у товара указано ведение учета по серийным номерам, если просканирован не серийный, а обычны шк товара то должно открыться окно выбора/создания и выбора серийного номера.

- [x] После сканирования ШК товара,
- [x] Открывается окно с надписью "просканируйте серийный номер".
- [x] После сканирования программа пытается найти этот серийный номер, если находит подсвечивает зеленым выбранный серийный номер и делает кнопку "Вырать" активной.
- [ ] Если серийный номер не найдет, программа выводит в список на экране ШК который пропикан кассиром (тут нужен контроль и игнор если кассир просканирует шк товара еще раз, так как шк расположены очень близко друг к другу).
- [ ] После того как кассир просканировал один или несколько серийных номеров или IMEI после нажатия на кнопку выбрать, программа создает и подставляет в табличную част серийный номер, а так же все ШК к нему в регистр ШК.

**Comment by DitriXNew** [comment]
@Severnity 
Обновить тесты.
Проверить отражение кнопки серий в справочниках

- [ ] Items
    **Должны быть видны серии которые** 
- [ ]    не имеют владельца 
- [ ]    владелец - вид открытого товара
- [ ]    владелец сам товар
- [ ]    по его ключам серии - не должно быть видно.

- [ ] ItemKeys
    **Должны быть видны серии которые** 
- [ ]    не имеют владельца 
- [ ]    владелец - вид открытого товара
- [ ]    владелец сам товар
- [ ]    Владелец - открытый ключ (т.е. других видно недолжно быть).

- [ ] ItemTypes
    **Должны быть видны серии которые** 
- [ ]    не имеют владельца 
- [ ]    владелец - текущий октрытый вид товара

**Comment by DitriXNew** [comment]
Тест штрихкодов - надо создать несколько штрикодов, часть только на товар, часть на серии.

- [ ] При сканировании штрихкода с серией - джолжны подставляться серии сразу.
- [ ] При сканировании штрихкода - без серии, должно появляяться окно ввода серии.

Тестировать сканирование товара с серией

- [ ] в документы, где серии не подключены, тогда просто должен подставить товар и ключ.

**Comment by DitriXNew** [comment]
Сделал пока универсально, без подбора существующих из списка, так как к этим пунктам есть вопросы.
Предлагаю эту задачу проанализировать, то что было сделано, закрыть, и потом точечно создать задачи по остальным пунктам.
