### ISSUE TITLE
Closing period

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#479]
Нужно добавить функционал установки периода "запрета/разрешения" исправления данных.

- [ ] - нужно устанавливать общий период огранчения исправления данных и частный для пользователя.
- [ ] - это должны быть именно периода, что бы можно было открыть к исправлению только 1 день в каком то месяце именно какому то пользователю.
- [ ] - Делать это документом, что бы иметь возможность учитывать кто, что, кому наразрешал.
- [ ] - по умолчанию функционал действует на документы, но при необходимости нужно что бы была ПРЕДУСМОТРЕНА 
возможность блокировать регистры (сделали сверки взаиморасчетов и по AP/AR уже ничего править нельзя, но если не меняя суммы и контрагента в открытом периоде у инвойса поменяется только товар, транзакция должна пройти, так как проводка по взаиморасчетам не будет задействована).
- [ ] - В документе должна быть дата окончания его действия. Т.е. я даю доступ за 21.01 - 24.01, и даю с 25.01 по 27.01. Т.е.  я даю возмоожность модифицировать некий период, только в указанные даты, т.е. после 27 числа - я не смогу модифицировать ничего в заднем периоде.

**Comment by Severnity** [comment]
реализован концепт
