### ISSUE TITLE
Зrohibition on creating catalog elements with the same name

### ISSUE THREAD

**Issue by gagmaz** [IRPTeam/IRP#480]
Запретить создание элементов справочников с одинаковым наименованием

**Comment by Teomit** [comment]
Проверка на дубли включена. Сейчас она работает для всех справочников, у которых задействуется Description или локализированные Description. В случае локализированных Description проверка работает сразу для всех заполненных значений - каждое значение проверяется для своего языка.
Для некоторых справочников проверка на дубли не нужна. Предлагаю в справочник ConfigurationMetada добавить реквизит проверки на дубли и на него ориентироваться при проверке на дубли.
