### ISSUE TITLE
Problem with overfilling in documents when entering the currency rate retroactively

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#49]
Сейчас есть проблема с перерасчетом сумм документов по курсам валют в случае если пользователь курс валют вносит задним числом

![изображение](https://user-images.githubusercontent.com/66120736/85862910-12ceac80-b7cb-11ea-9248-51291563824f.png)

Например, пользователь создал Sales invoice. На момент создания документа в базе был актуальный курс 0,1770. Далее пользователь понимает, что он забыл заполнить курс валют и задним числом вносит курс 0,1700, который становится актуальным для созданного Sales invoice. Для того чтобы курс в Sales invoice стал 0,1700 необходимо в него зайти и поменять курс вручную. И так по всем документам в которых есть вкладка Currency:

- [ ] Sales order
- [ ] Sales invoice
- [ ] Purchase order
- [ ] Purchase invoice
- [ ] Purchase return order
- [ ] Purchase return
- [ ] Sales return order
- [ ] Sales return
- [ ] Cash payment
- [ ] Cash receipt
- [ ] Bank payment
- [ ] Bank receipt
- [ ] Cash expense
- [ ] Cash revenue
- [ ] Cash transfer order
- [ ] Credit debit note
- [ ] Invoice match
- [ ] Cheque bond transaction
- [ ] Incoming payment order
- [ ] Outgoing payment order

Нужно автоматизировать решение такой ситуации.

**Comment by DitriXNew** [comment]
Не понял, звучит противоречиво.
Можно пример с цифрами, типо вот я создал 5 числа, курс был так, потом ....

**Comment by Severnity** [comment]
Валюта отчетности - доллары
Установленный курс на 01.06 - 25 грн за 1 дол
05.06 провожу Sales invoice на 1000 грн (сумма в валюте отчетности 40 дол)
10.06 понимаю, что забыла заполнить курс на 04.06 и он должен быть не 25 грн за 1 дол, а 26 грн за 1 дол. Захожу в регистр и вношу курс на 04.06 - 26 грн за 1 дол. Теперь мне нужно чтобы сумма Sales invoice от 05.06 в валюте отчетности стала не 40 дол, 38,46 дол.

**Comment by bryaleks** [comment]
без четкого указания со стороны пользователя в документах не должно ничего меняться. тут я думаю нужен отчет который будет показывать расхождения курсов в документах с курсами актуальными на дату документа по видам валютных аналитик которые указаны в документе.

**Comment by DitriXNew** [comment]
Задача не актуальна. Ждем реального кейса.
