### ISSUE TITLE
Cash payment (POS)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#495]
При оплате налом в POS возникает ошибка
Object field not found (Description)
{DataProcessor.PointOfSale.Form.Payment.Form(116)}:	
![изображение](https://user-images.githubusercontent.com/66120736/97144117-8deda280-176c-11eb-88c0-4c76eff49740.png)

**Comment by Teomit** [comment]
Не воспроизводится на базе, где возникла ошибка.
