### ISSUE TITLE
Error with additional attributes output in html field

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#52]
В html поле по Item доп реквизиты выводятся в не зависимости от того присущи ли они данному item или нет.

Например, для услуг нет доп реквизитов Country of consignment и Brand
![изображение](https://user-images.githubusercontent.com/66120736/85865891-40b5f000-b7cf-11ea-8a0e-d494ed86fcdc.png)
![изображение](https://user-images.githubusercontent.com/66120736/85865980-6642f980-b7cf-11ea-81d1-e1baa8846e7b.png)

**Comment by DitriXNew** [comment]
@Teomit @andreyvorobyov2 ищу функцию чтобы я послал туда ссылку на справочник, а она мне вернула таблицу доступных свойств, в том числе и пустых

**Comment by Severnity** [comment]
@Teomit тесты словили ошибку с обязательным заполнением доп реквизита у item key
Раньше если пользователь в item key не заполнял обязательный реквизит появлялось сообщение Field [Season] is empty.
Сейчас выскакивает ошибка
 Object field not found (IsConditionSet)
{CommonModule.AddAttributesAndPropertiesServer.Module(413)}:        If Row.IsConditionSet Then
{CommonModule.AddAttributesAndPropertiesServer.Module(388)}:        FillTableOfAvailableAttributesBy_AllItems(TableOfAvailableAttributes
{CommonModule.AddAttributesAndPropertiesServer.Module(680)}:            ReducedObjectAttributes = ReduceObjectAttributes(FormInfo, AddAttributeAndPropertySetsAttributesByFilter, ObjectPredefinedName);
{CommonModule.AddAttributesAndPropertiesServer.Module(22)}:    RequiredAttributesArray = AllAttributesArrayByFilter(CurrentObject, RequiredFiler);
{Catalog.ItemKeys.Form.ItemForm.Form(128)}:        AddAttributesAndPropertiesServer.BeforeWriteAtServer(ThisObject, Cancel, CurrentObject, WriteParameters);

и доп реквизиты в html поле по айтем ки перестали отображаться
таже ошибка
