### ISSUE TITLE
Prices in purchase invoice

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#540]
При изменении даты, программа спрашивает пересчитать ли цены. Это очень раздражает, так как в программе цены не ведутся и приходится постоянно снимать галочки. Можно спрашивать такие вещи в случае, если в программе есть какие то цены на номенклатуру по типу цен поставщика (Зачастую поступления добавляются копированием).

**Comment by Severnity** [comment]
в случае если пользователь не хочет вести цены по поставщику, то в соглашении он выбирает вид цены Manual. При таком виде цен при изменении даты запроса на пересчет не будет. 
Если в документе пользователь вручную выберет по строке вид цены, то при изменении даты отобразится запрос на пересчет.
