### ISSUE TITLE
Individual unit creation

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#545]
- [x] При использовании индивидуальных единиц измерения для айтема необходимо добавить возможность создания индивидуальной единицы измерения с использованием Basis unit которым будет вторая индивидуальная единица измерения этого же айтема
![image](https://user-images.githubusercontent.com/66120736/98226157-55b14580-1f5e-11eb-9f1c-7daf78c26b55.png)
в списке выбора должна быть доступна единица измерения ind 1

**Comment by DitriXNew** [comment]
По второму пункту - а как мы узнаем, что они хотят создать новый именно индивидуальный?
Предлагаю пока оставить как есть.

**Comment by bryaleks** [comment]
> По второму пункту - а как мы узнаем, что они хотят создать новый именно индивидуальный?
> Предлагаю пока оставить как есть.

Ну например можно спросить.
