### ISSUE TITLE
Driver install 

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#548]
При установке драйвера в случае если драйвер не выбран возникает ошибка
Index outside array bounds
{CommonModule.HardwareClient.Module(25)}:    ObjectName.Add(ObjectName[1]);
{Catalog.EquipmentDrivers.Form.ItemForm.Form(92)}:    HardwareClient.BeginGetDriver(Оповещение, ДанныеДрайвера);
{Catalog.EquipmentDrivers.Form.ItemForm.Form(184)}:    UpdateDriverStatus();
{mngcore/MessageBox.clf(4)}:    Close(-100);

**Comment by DitriXNew** [comment]
Добавил контроль и сообщения при установке и при записи
