### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#55]
В справочнике Files перестала работать кнопка Create preview
Также для оптимизации скорости вывода картинок необходимо сделать так что бы превью картинок хранились в базе

**Comment by DitriXNew** [comment]
![image](https://user-images.githubusercontent.com/11927866/85999305-c2b93b00-b9c0-11ea-9b8a-044222690a09.png)
Теперь привью жестко записываются в базу.
Есть два реквизита:
Preview - хранилище, тут лежит бинарник самого сжатого изображения
isPreviewSet - флаг, ставим истину, если картинка есть, ложь - если картинки нету.

Сжатие идет до 200px по большей стороне.

Проблема такого подхода  - сжатие работает на стороне сервера, а значит, если будет огромная картинка, то ее надо будет передавать на сервер для сжатия, что замедлит быстродействие.
@Severnity @Teomit @andreyvorobyov2
