### ISSUE TITLE
Error when click Test in Hardware

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#570]
При нажатии на кнопку Test при создании оборудования возникает ошибка
Cannot call synchronous methods on the client!
{IRP_AdditionalFunctionality CommonModule.HardwareInputDevice.Module(125)}:			Response = DriverObject.УстановитьПараметр(ParameterName, ParameterValue); 
{IRP_AdditionalFunctionality CommonModule.HardwareInputDevice.Module(53)}:		Result = TestDevice(DriverObject, Parameters, ConnectionParameters, OutParameters);
{CommonModule.HardwareClient.Module(118)}:		Result = ProcessingModule.RunCommand(CommandParameters.Command, CommandParameters.IncomingParams,
{CommonModule.HardwareClient.Module(42)}:		ExecuteNotifyProcessing(AddInfo.NotifyOnClose, DriverObject);

, reason:
Cannot call synchronous methods on the client!
![image](https://user-images.githubusercontent.com/66120736/98852184-f7a1c800-245f-11eb-818b-ce020670fb6f.png)

**Comment by Teomit** [comment]
Ошибка возникала из-за того, что у конфигурации был установлен признак запрета использования синхронных вызовов. На данный момент в конфигурации разрешено использование синхронных вызовов для совместимости с драйверами.
