### ISSUE TITLE
Add Reference to list and choice forms and set it.

### ISSUE THREAD

**Issue by Teomit** [IRPTeam/IRP#579]
Добавить поле Reference во все формы выбора и списков. 
Поле скрыть через условное оформление списка. В этом случае пользователь сможет пользоваться данным полем для добавление реквизитов на форму через её ссылку.
Пример: справочник Companies, форма ListForm.

Добавить во всех динамических списках запрос, который будет вытягивать Description на английском языке, и пропускать этот запрос через локализатор, который будет туда подставлять язык пользователя.
При выводе этого поля на форму - обязательно писать Title, так и писать Description. Иначе, этот заголовок не будет переводиться на другие языки.

Проверить остальные поля, которые добавлены произвольно, что у них у все будет заголовок при выводе на форму.
Например, если поле Дата отгрузки, если оно являетсяреквизитом главной таблицы запроса, то заголовок должен быть пустым, тогда он подтянется из заголовка самого реквизита. И наоборот, если это поле является рассчетным, то тогда обязательно должен быть указан заголовок.

**Comment by Teomit** [comment]
Проверить остальные поля, которые добавлены произвольно, что у них у все будет заголовок при выводе на форму.
Например, если поле Дата отгрузки, если оно являетсяреквизитом главной таблицы запроса, то заголовок должен быть пустым, тогда он подтянется из заголовка самого реквизита. И наоборот, если это поле является рассчетным, то тогда обязательно должен быть указан заголовок.

**Comment by Severnity** [comment]
@Teomit необходимо доделать

**Comment by bryaleks** [comment]
список выбора ItemKey

**Comment by Severnity** [comment]
@DitriXNew в этих формах ссылки не хватает
![image](https://user-images.githubusercontent.com/66120736/109272679-e667a600-7819-11eb-94cd-ecb40cfb1d7f.png)
![image](https://user-images.githubusercontent.com/66120736/109272719-eff10e00-7819-11eb-91f2-d78770952d07.png)
![image](https://user-images.githubusercontent.com/66120736/109272740-f8494900-7819-11eb-8a35-ac51e6743b60.png)
![image](https://user-images.githubusercontent.com/66120736/109272836-17e07180-781a-11eb-978e-3a271e75946a.png)
![image](https://user-images.githubusercontent.com/66120736/109272871-20d14300-781a-11eb-8810-fbda5ded77ff.png)
