### ISSUE TITLE
Search by string

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#58]
Ранее у нас при вводе по строке (legal name, item и item key) подставлялось наиболее подходящее точное значение.
Например, создаю заказ клиента
Выбираю Partner - Ferron BP (у него есть 2 Legal name: Company Ferron BP и Second  Company Ferron BP)
В поле Legal name ввожу по строке Company Ferron BP
Ранее мне первым в списке выбора предлагало наиболее подходящее значение -  Company Ferron BP, сейчас стало предлагать Second  Company Ferron BP
![изображение](https://user-images.githubusercontent.com/66120736/85922760-78d03800-b88e-11ea-9aec-0f109801bd5d.png)
Аналогичная проблема с Item и item key
![изображение](https://user-images.githubusercontent.com/66120736/85922799-b7fe8900-b88e-11ea-9f5d-e6b74ab8dee5.png)
![изображение](https://user-images.githubusercontent.com/66120736/85922807-c64ca500-b88e-11ea-95ed-de0089d9e0a8.png)

**Comment by DitriXNew** [comment]
Создал новую функцию для поиска по строке, пример вызова:
```bsl
	Filter = "
		|	AND CASE
		|			WHEN &FilterByPartnerHierarchy
		|				THEN Table.Ref IN (&CompaniesByPartnerHierarchy)
		|			ELSE TRUE
		|		END
		|";
	QueryBuilderText = LocalizationEvents.ReplaceDescriptionLocalizationPrefix(QueryBuilderText);
		|		WHEN &FilterByPartnerHierarchy
		|			THEN Table.Ref IN (&CompaniesByPartnerHierarchy)
		|		ELSE TRUE
		|	END";
	Settings = New Structure;
	Settings.Insert("Name", "Catalog.Companies");
	Settings.Insert("Filter", Filter);
	
	QueryBuilderText = CommonFormActionsServer.QuerySearchInputByString(Settings);
```

Теперь отбирается топ 10 по левому соответствию строке, потом по любому, кроме левого.
И потом берется топ 10 из них по сортировке с приоритетом ввода по началу строки.

@Severnity @andreyvorobyov2 @Teomit
