### ISSUE TITLE
Add user in the 2 access groups (system set roles only from last)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#583]
В случае если пользователь был добавлен в 2 группы доступа с разными профилями (ролями), то роли из двух групп доступа должны суммироваться.
Роли группы доступа из которой пользователя удалили для него действовать не должны

**Comment by DitriXNew** [comment]
@Severnity надо сделать еще тест на случай, когда из группы исключен пользователь. Тогда должны быть исключены права из той группы доступа.
