### ISSUE TITLE
Company in Stores

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#589]
Нужно добавить реквизит организации в склады и сделать проверку при проведении складских документов.
Если у склада указана организация, документы не должны проходить проверку если в доке указана другая организация.
Если у склада нет организации, значит это общий склад для двух организаций

**Comment by Severnity** [comment]
+ не показывать в списке выбора недоступный склад

**Comment by Severnity** [comment]
нужно применить ко всем документам у которых есть организация и склад
