### ISSUE TITLE
Item unit selection (storage)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#596]
В форме выбора единицы хранения в Item и Item key не должны отображаться единицы у которых указан Basis unit, а также те которые не кратны 1иначе возникает ошибка с созданием на основании (не правильно срабатывает пересчет)
https://github.com/IRPTeam/IRP/issues/585
![image](https://user-images.githubusercontent.com/66120736/99954411-5c77ef00-2d8b-11eb-948c-a71b4808f195.png)

**Comment by Severnity** [comment]
можно поставить проверку перед записью. Плюс поставить проверку у юнита что если он где-то использован, то нельзя было менять у него коэфицент.

**Comment by DitriXNew** [comment]
Добавил контроль выбора из форм товара и ключа

**Comment by DitriXNew** [comment]
Для контроля - добавил кнопку.
![изображение](https://user-images.githubusercontent.com/11927866/101375728-cd0d2880-38c0-11eb-8d70-bd2298e2a211.png)

При создании нового элемента - все реквизиты разблокированы
При открытии существующего - по умолчанию срабатывает блокировка реквизитов
При нажатии на разблокирование - система показывает в каком количестве мест используется эта ссылка, и приводит в пример 5 первых мест.

**Comment by DitriXNew** [comment]
дополнительные исправления - в документе, при выборе юнитов отрабатывает фильтр новый, он выбирает только юниты у которых владелец этот товар и юнит который явно указан у этого товара.

**Comment by DitriXNew** [comment]
Надо детально подумать про юниты в ключах, возможно от них надо отказаться
