### ISSUE TITLE
Tests for lock data

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#598]
Надо написать тесты на модификацию данных.

- [ ] Система должна работать с неполными правами, Т.е. с начальными
- [x] К системе должен иметь доступ пользователь с правами на чтение
При выключенной функциональной опции:
    - [x] в независимости от того - есть правила или нет, если опция выключена - правила не должны работать
    - [x] не должны быть видны подсистемы, и ее элементы
Включаем опцию - убедимся, что что появились все подсистемы и объекты.

- [x] Создаем первую настройку и справочник причин. Убедимся что после сохранение и переоткрытия - все данные остались
![изображение](https://user-images.githubusercontent.com/11927866/100015578-dedece00-2de0-11eb-9307-d268a275169b.png)

Создаем правила на все вариации, пока кроме - BETWEEN и NULL на некий справочник, и проверяем что они работают.
![изображение](https://user-images.githubusercontent.com/11927866/100015746-1d748880-2de1-11eb-8ee9-a4e019a9952d.png)

Создаем правила на "=" и "in" на один реквизит каждого:
- [x] Справочник
- [x] Документ
- [x] Регистр накоплений
- [x] Регистр сведений подчиненный
- [x] Регистр сведений не подчиненный
Т.е. в итоге 10 правил.

Каждое правило проверяем на:
- [x] Модификацию данных
- [x] Создание нового объекта
- [x] Удаление объекта из базы (это можно пока тупо вручную проверить)

- [x] На 2 условиях проверяем что срабатывает галочка Disable в правилах, т.е. если она включена - правило не работает.

- [x] При срабатывании условия - должно появится сообщение с причиной:
![изображение](https://user-images.githubusercontent.com/11927866/100016306-e05cc600-2de1-11eb-8859-459a66e08b13.png)

- [x] Делаем проверку на реквизите - который добавили через расширение

- [x] Делаем проверку на добавленный справочник через расширение (можно вручную)

**Comment by Severnity** [comment]
@DitriXNew у меня не отработало:
1. значение IN HIERARCHY на запись нового объекта (задача https://github.com/IRPTeam/IRP/issues/604, тест с тегом @AccessRights номер 950417 create rules for catalog (IN HIERARCHY)
2. выбор значения IN для справочника (если выбираю папку) - задача https://github.com/IRPTeam/IRP/issues/603
Условия на добавленный справочник через расширение проверяла вручную.
