### ISSUE TITLE
Amount calculation according to currency rate

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#635]
Не корректно рассчитываются валютные сумма.
Загружены курсы:
![image](https://user-images.githubusercontent.com/32883592/101388233-b79ffa80-38d0-11eb-9933-2a5a94cf4555.png)

При вводе инвойса на 2.000 долларов, не корректно пересчитывается сумма

![image](https://user-images.githubusercontent.com/32883592/101388317-d605f600-38d0-11eb-9bbb-0ea9aa2e3199.png)

**Comment by DitriXNew** [comment]
Добавил в отборы источника курса - чтобы брались только сетинги с типом - загрузка курсов
