### ISSUE TITLE
Fill ConfigurationMetadata catalog from configuration

### ISSUE THREAD

**Issue by Teomit** [IRPTeam/IRP#640]
- [x] Добавить в справочник ConfigurationMetadata кнопку автозаполнения на основе данных конфигурации.

**Comment by Teomit** [comment]
Добавить регламентное задание или проверку при старте на соответствие элементов справочника метаданным конфигурации в отдельную задачу.

**Comment by Teomit** [comment]
В справочнике ConfigurationMetadata в форме списка есть кнопка заполнения элементов значениями метаданных из базы. Если в процессе заполнения не обнаружено значение метаданных для существующего элемента справочника, то в элементе устанавливается признак Unused.

**Comment by Severnity** [comment]
при повторном нажатии на кнопку заполнения элементов возникает ошибка Object method not found
![image](https://user-images.githubusercontent.com/66120736/101644721-3797a300-3a3e-11eb-90ba-698a9e3808cd.png)
Также галочка Unused проставляется у всех атоматически заполненных элементов ( через кнопку Refill metadata)
