### ISSUE TITLE
Groups in AddAttributeAndProperty

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#668]
Нужно сделать справочник иерархическим, потому что трудно ориентироваться когда несколько десятков доп реквизитов.

**Comment by bryaleks** [comment]
Можно доп реквизитами

**Comment by DitriXNew** [comment]
@Severnity написать тест, где два реквизита будут находиться внутри группы, и два - вне группы. Чтобы отловить потенциальные проблемы.

**Comment by bryaleks** [comment]
это про ChartOfCharacteristicTypes.AddAttributeAndProperty
