### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#687]
Необходимо добавить функционал работы с дисконтами
Клиенту выдается накопительная дисконтная карта, например на 5%. По мере накопления суммы продажи дисконт увеличивается. Например, при 50 тыс. дисконт стает 7%.
При проведении продажи продавец сканирует дисконтную карту и покупателю начисляется скидка

**Comment by bryaleks** [comment]
@DitriXNew надо концепт уточнить
