### ISSUE TITLE
Кнопка Select Goods receipt в Purchase invoice

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#7]
При заполнении товара в Purchase invoice через кнопку Select goods receipt не переносятся Goods receipt с одинаковыми товарами (переносится только один из них)
1. Пользователь создает Purchase order на 2 товара (Dress TR S/Yellow TR - 100 шт., XS/Blue TR - 100 шт.
2. Создает на основании  Purchase order на частичную отгрузку товаров (один на Dress TR S/Yellow TR - 40 шт., XS/Blue TR - 70 шт., второй на Dress TR S/Yellow TR - 60 шт., XS/Blue TR - 30 шт.)
3. Создает Purchase invoice и подбирает товары из  Goods receipt  (нажимает кнопку Select goods receipt)
4. Выбирает 2 созданных Goods receipt, но переносится только один
Нужно сделать так, чтобы переносился товар из двух Goods receipt
![image](https://user-images.githubusercontent.com/66120736/83722894-70496080-a646-11ea-89c0-bbcef90af5f6.png)
![image](https://user-images.githubusercontent.com/66120736/83722924-79d2c880-a646-11ea-987c-51b8db8c3d21.png)

**Comment by DitriXNew** [comment]
Вот тут бы отлично демо базу и сказать какой сценарий покрывает этот тест @Severnity

**Comment by andreyvorobyov2** [comment]
исправлено по задаче #246 

Выбранные документы Goods receipt отображаются на соотвествующей вкладке, на вкладке Item list количество суммируется по товарам.

![image](https://user-images.githubusercontent.com/66310255/94279617-06d2c200-ff55-11ea-9f4f-dd33d04123c4.png)

![image](https://user-images.githubusercontent.com/66310255/94279640-1225ed80-ff55-11ea-8c9c-661aca6cc592.png)

![image](https://user-images.githubusercontent.com/66310255/94279672-1c47ec00-ff55-11ea-891b-c2bc72243cce.png)
