### ISSUE TITLE
Dependent prices are not calculated (by item key and by property)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#70]
В обработке по расчету зависимой цены в прайс листе перестала отрабатывать настройка заполнения по item key и по property
Пользователь создает Price list и выбирает вид цены по которому цены рассчитываются с помощью обработки исходя из другого вида цен (указывается в виде цен). В тестовой базе это Depended price
Меняет переключатель Set price на by item keys
Нажимает кнопку Fill by rules
В открывшемся окне меняет переключатель 'PriceListType' на 'By Item keys'
Ставит галочку Use возле Basic price type и нажимает Ок
Цены в прайс листе по item key не рассчитываются. Аналогично если установить переключатель 'PriceListType' на 'By property'
![изображение](https://user-images.githubusercontent.com/66120736/86013654-0dba6900-ba28-11ea-9ef5-be35214b3206.png)
Расчет цен происходит только если переключатель 'PriceListType' равен 'By items'

Тест для проверки 016010. С шага  Проверка расчета зависимой цены в прайс листе. (в тестовой базе предварительно нужно проверить чтобы был проведен прайс лист №100)

**Comment by DitriXNew** [comment]
Это ошибка компиляции обработки, уже исправил
