### ISSUE TITLE
Error with message output on special offers type Special Message Notification

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#71]
При назначении скидки вида Special Message Notification вместо нужного сообщения которое заполнил пользователь в сообщениях выводится текст Structure
Специальное предложение назначается с помощью обработки ExternalSpecialMessage
В тестовой базе это специальное предложение Special Message Notification
![изображение](https://user-images.githubusercontent.com/66120736/86015386-2af03700-ba2a-11ea-97cb-518e406bb243.png)

![изображение](https://user-images.githubusercontent.com/66120736/86014713-5b83a100-ba29-11ea-90bc-daa8cea16da7.png)

![изображение](https://user-images.githubusercontent.com/66120736/86014556-29723f00-ba29-11ea-9489-cbe201e49441.png)

**Comment by DitriXNew** [comment]
исправил, кто то переписал обработку на многоязычность, и не проверил...
