### ISSUE TITLE
Change SO procurement

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#713]
CurrentStockRezerve - Со склада в резерв (сразу резервируется товар).
ProcureViaPurchaseOrder - Под закупку (запускается процесс обеспечения SO через PO)
FirstStockRezerve - На складе нет, но резервирует первый пришедший остаток. Кейс когда в заказе 10, а в свободном остатке 7, при выборе 7 уйдут в резерв сразу, а 3 при первом приходе товара.
NoRezerve - Без резерва (строка активна, но не делает ни резерва ни каких то других операций).

Boolean Cancel - Отмена строки, при Cancel=True обязательно выбирать причину отмены).

**Comment by DitriXNew** [comment]
> FirstStockRezerve - На складе нет, но резервирует первый пришедший остаток. Кейс когда в заказе 10, а в свободном остатке 7, при выборе 7 уйдут в резерв сразу, а 3 при первом приходе товара.

На этот пункт надо отдельную задачу

**Comment by Severnity** [comment]
пункт по FirstStockRezerve вынесен в отдельную задачу
https://github.com/IRPTeam/IRP/issues/732
