### ISSUE TITLE
New registers

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#720]
- [x] в Register  "R1014 Canceled purchase orders" не записывается сумма

![image](https://user-images.githubusercontent.com/66120736/103992814-5902c080-519d-11eb-8654-5e2b31ded63d.png)

**Comment by Severnity** [comment]
- [ ] по Sales invoice в регистр R2001 Sales не записывается сумма
![image](https://user-images.githubusercontent.com/66120736/103993048-a8e18780-519d-11eb-86ab-8acc4c39c982.png)

**Comment by Severnity** [comment]
- [ ] Sales invoice по Stock inventory должен делать расход (сейчас делает приход)
![image](https://user-images.githubusercontent.com/66120736/103993150-d4647200-519d-11eb-86ee-4223840619d2.png)

**Comment by Severnity** [comment]
- [ ] Purchase invoice по новым регистрам проводки не делает

**Comment by Severnity** [comment]
- [ ] Good receipt в случае если в нем указан PI должен делать расход по R1031B_ReceiptInvoicing, сейчас делает приход и в Basis должен быть PI
![image](https://user-images.githubusercontent.com/66120736/103993472-55236e00-519e-11eb-9c81-1f943f60b9be.png)
![image](https://user-images.githubusercontent.com/66120736/103993611-8bf98400-519e-11eb-8594-c3c601602153.png)

**Comment by Severnity** [comment]
- [ ] если в SO/PO только 1 отмененная строка, то на его основании дает создать SC/SI и PO/PI

**Comment by Severnity** [comment]
- [ ] не выполняется проводка
![image](https://user-images.githubusercontent.com/66120736/103994418-a718c380-519f-11eb-8eae-8f09347d52c5.png)

**Comment by Severnity** [comment]
- [ ] PO в случае если он создан на основании SO не делает проводку в R2013T_SalesOrdersProcurement

**Comment by Severnity** [comment]
- [ ] в случае если в SI есть скидка в регистр R2005T_SalesSpecialOffers не записывается Sales amount, Net amount, Net offer amount

![image](https://user-images.githubusercontent.com/66120736/103996169-21e2de00-51a2-11eb-8fd3-4e8ab54e1769.png)

**Comment by Severnity** [comment]
- [ ] SI не должен делать движения по регистру Register  "R2013 Procurement of sales orders" (SI создан на основании SO c методом обеспечения Stock)

**Comment by Severnity** [comment]
- [ ] SI не записывает сумму в регистр Register  "R2012 Invoice closing of sales orders"

![image](https://user-images.githubusercontent.com/66120736/103996783-fdd3cc80-51a2-11eb-9463-96b5490794b7.png)

**Comment by Severnity** [comment]
- [ ] SI не делает движения в регистр R2021B_CustomersTransactions

**Comment by Severnity** [comment]
- [ ] при создании SI на основании SO безе перевыбора соглашения не заполняется вкладка Aging

**Comment by Severnity** [comment]
- [ ] SC не делает проводки по регистрам R2011B_SalesOrdersShipment, R2031B_ShipmentInvoicing, R2031B_ShipmentInvoicing, R4022B_StockTransferOrdersShipment, R4034B_GoodsShipmentSchedule

**Comment by DitriXNew** [comment]
> * [x]  Good receipt в случае если в нем указан PI должен делать расход по R1031B_ReceiptInvoicing, сейчас делает приход и в Basis должен быть PI
> https://github.com/IRPTeam/IRP/issues/720#issuecomment-756629135

Да, тут надо смотреть на другое поле.

**Comment by DitriXNew** [comment]
> * [x]  не выполняется проводка
>   https://github.com/IRPTeam/IRP/issues/720#issuecomment-756633053

Выполняется, там отдельное поле для этого документа

**Comment by DitriXNew** [comment]
> * [ ]  PO в случае если он создан на основании SO не делает проводку в R2013T_SalesOrdersProcurement

это проблема того, что там заполение идет со старого регистра и не заполняется поле SO

**Comment by DitriXNew** [comment]
> * [ ]  SI не должен делать движения по регистру Register  "R2013 Procurement of sales orders" (SI создан на основании SO c методом обеспечения Stock)

Почему не должен? Там же отдельное поле для этого есть, там шипмент отдельно ложит, инвойс - отдельно

**Comment by DitriXNew** [comment]
> * [ ]  SI не делает движения в регистр R2021B_CustomersTransactions (аванса нет)

по фин пока не делали

**Comment by DitriXNew** [comment]
> * [x]  при создании SI на основании SO безе перевыбора соглашения не заполняется вкладка Aging

это не к новым регистрам

**Comment by DitriXNew** [comment]
> * [ ]  SC не делает проводки по регистрам R2011B_SalesOrdersShipment, R2031B_ShipmentInvoicing, R2031B_ShipmentInvoicing, R4022B_StockTransferOrdersShipment, R4034B_GoodsShipmentSchedule

Там везде отдельный поля, собственно если они заполнены, то движения проходят

``` bsl
Function R2011B_SalesOrdersShipment()
	Return
		"SELECT 
		|	VALUE(AccumulationRecordType.Expense) AS RecordType,
		|	QueryTable.SalesOrder AS Order,
		|	*
		|INTO R2011B_SalesOrdersShipment
		|FROM
		|	ItemList AS QueryTable
		|WHERE QueryTable.SalesOrderExists";

EndFunction

Function R2013T_SalesOrdersProcurement()
	Return
		"SELECT
		|	QueryTable.Quantity AS ShippedQuantity,
		|	QueryTable.SalesOrder AS Order,
		|	*
		|INTO R2013T_SalesOrdersProcurement
		|FROM
		|	ItemList AS QueryTable
		|WHERE
		|	QueryTable.SalesOrderExists";

EndFunction

Function R2031B_ShipmentInvoicing()
	Return
		"SELECT 
		|	VALUE(AccumulationRecordType.Receipt) AS RecordType,
		|	QueryTable.ShipmentConfirmation AS Basis,
		|	QueryTable.Quantity AS Quantity,
		|	QueryTable.Company,
		|	QueryTable.Period,
		|	QueryTable.ItemKey
		|INTO R1031B_ReceiptInvoicing
		|FROM
		|	ItemList AS QueryTable
		|WHERE NOT QueryTable.SalesInvoiceExists
		|
		|UNION ALL
		|
		|SELECT 
		|	VALUE(AccumulationRecordType.Expense),
		|	QueryTable.SalesInvoice,
		|	QueryTable.Quantity,
		|	QueryTable.Company,
		|	QueryTable.Period,
		|	QueryTable.ItemKey
		|FROM
		|	ItemList AS QueryTable
		|WHERE QueryTable.SalesInvoiceExists";

EndFunction

Function R4010B_ActualStocks()
	Return
		"SELECT
		|	VALUE(AccumulationRecordType.Expense) AS RecordType,
		|	*
		|INTO R4010B_ActualStocks
		|FROM
		|	ItemList AS QueryTable
		|WHERE TRUE";

EndFunction

Function R4022B_StockTransferOrdersShipment()
	Return
		"SELECT 
		|	VALUE(AccumulationRecordType.Expense) AS RecordType,
		|	QueryTable.InventoryTransferOrder AS Order,
		|	*
		|INTO R4022B_StockTransferOrdersShipment
		|FROM
		|	ItemList AS QueryTable
		|WHERE QueryTable.InventoryTransferOrderExists";

EndFunction

Function R4034B_GoodsShipmentSchedule()
	Return
		"SELECT 
		|	VALUE(AccumulationRecordType.Expense) AS RecordType,
		|	QueryTable.SalesOrder AS Basis,
		|	*
		|INTO R4034B_GoodsShipmentSchedule
		|FROM
		|	ItemList AS QueryTable
		|WHERE QueryTable.SalesOrderExists
		|	AND QueryTable.SalesOrder.UseItemsShipmentScheduling";

EndFunction

```
