### ISSUE TITLE
Repeal is not Cancel

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#722]
Когда в SO no rezerve не отрабатывает создание на основании SI

**Comment by Severnity** [comment]
при попытке создания SI не отрабатывает
при попытке создания SC выдает сообщение о том, что товар ещё не заказн у поставщика
![image](https://user-images.githubusercontent.com/66120736/104285492-6335ff00-54bc-11eb-880c-17d264751cde.png)
