### ISSUE TITLE
String add attribute type for Item key

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#753]
В случае если в состав айтем ки входит доп реквизит с типом строка, при записи атем ки возникает ошибка

Error running processor - 'BeforeWrite'
, reason:
Value is not of object type (Metadata)
{CommonModule.LocalizationServer.Module(39)}:	If Not UseMultiLanguage(Ref.Metadata().FullName(), LangCode, AddInfo) Then
{CommonModule.LocalizationReuse.Module(6)}:	Return LocalizationServer.CatalogDescription(Ref, LangCode, AddInfo);
{CommonModule.LocalizationServer.Module(59)}:			PresentationAttribute = LocalizationReuse.CatalogDescription(AddAttribute.Value, LangCode, AddInfo);
{Catalog.ItemKeys.ManagerModule(244)}:			NewName = LocalizationServer.CatalogDescriptionWithAddAttributes(ItemKeyObject, StrSplit(Lang, "_")[1]);
{Catalog.ItemKeys.ObjectModule(107)}:	Catalogs.ItemKeys.UpdateDescriptions(ThisObject);

**Comment by DitriXNew** [comment]
Не смог воспроизвести, прошу перепроверить

**Comment by Severnity** [comment]
уже не актуально
