### ISSUE TITLE
Pick up items from basis documents

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#769]
В документы в которых есть row key и в которых есть связь с документом-основанием необходимо добавить форму по подбору товаров и заполнения документа-основания. По аналогии как сделано в GR.
При подборе строк row key должен заполняться такой же как в документе-основания. 

Иначе возникает проблема когда пользователь удаляет строку, а потом её добавляет заново (не совпадают row key)

**Comment by bryaleks** [comment]
В связи с новым механизмом ввода на основании потеряло акуальность
