### ISSUE TITLE
SC has more Q then SO

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#772]
При создании SC на основании SO дает возможность отгузить больше чем в заказе несмотря на запрет в найтройках пользователя

**Comment by Severnity** [comment]
скорее всего неполный запрет стоит (не все галочки контроля в настройках пользователя)

**Comment by bryaleks** [comment]
Проблемы в проводках, когда нет запрета пользователя на отгрузку больше чем в заказе, если в строке указано больше нужно что бы логика отрабатывала по заказу. В SI учитываем колво из SC.
