### ISSUE TITLE
Add serial number at opening entry

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#775]
- [x] PurchaseInvoice
- [ ] PurchaseReturn
- [x] SalesInvoice
- [x] SalesReturn
- [x] OpeningEntry
- [x] ItemStockAdjustment
- [x] StockAdjustmentAsSurplus
- [x] StockAdjustmentAsWriteOff
- [ ] RetailSalesReceipt
- [ ] RetailReturnReceipt

**Comment by DitriXNew** [comment]
- [ ] PurchaseInvoice
- [ ] PurchaseReturn
- [ ] SalesInvoice
- [ ] SalesReturn
- [ ] OpeningEntry
- [ ] ItemStockAdjustment
- [ ] StockAdjustmentAsSurplus
- [ ] StockAdjustmentAsWriteOff
- [ ] RetailSalesReceipt
- [ ] RetailReturnReceipt

**Comment by Severnity** [comment]
- [ ] Purchase invoice по регистру R4014 Serial lot numbers должен делать приход, сейчас делает расход

**Comment by Severnity** [comment]
- [ ] в документах PurchaseInvoice, PurchaseReturn, OpeningEntry, ItemStockAdjustment, StockAdjustmentAsSurplus, StockAdjustmentAsWriteOff нужно добавить контроли на заполнение серий

**Comment by Severnity** [comment]
- [ ] при создании Purchase return на основании Purchase invoice серии не переносятся

**Comment by Severnity** [comment]
серийные номера по документам добавлены
нужна доработка с движениями и формами выбора серий
https://github.com/IRPTeam/IRP/issues/784
