### ISSUE TITLE
Attaching external files to documents and catalogs

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#78]
Необходимо добавить функционал который позволит прикреплять к документам и справочникам внешние файлы (сканы), а также просматривать такие файлы.
Нужно также предусмотреть, что сканы документов могут храниться на одном гугл аккаунте а фото товаров на другом
В первую очередь актуально для:

- [x] Purchase invoice
- [x] Sales return order
- [x] Sales return
- [x] Reconcilation statement
- [x] Company
- [x] Partners
- [x] Agreements

**Comment by DitriXNew** [comment]
@Severnity  https://github.com/IRPTeam/IRP/pull/1135 обновить тесты, описание в пуле
