### ISSUE TITLE
Store in the List form

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#795]
По документам в которых есть склады необходимо склад вынести в форму списка

**Comment by DitriXNew** [comment]
@Severnity проверь на всякий - не пропустил ли ничего?

- [ ] GoodsReceipt
- [ ] OpeningEntry
- [ ] PlannedReceiptReservation
- [ ] PurchaseInvoice
- [ ] PurchaseOrder
- [ ] PurchaseOrderClosing
- [ ] PurchaseReturn
- [ ] RetailReturnReceipt
- [ ] RetailSalesReceipt
- [ ] SalesInvoice
- [ ] SalesOrder
- [ ] SalesOrderClosing
- [ ] SalesReturn
- [ ] SalesReturnOrder
- [ ] ShipmentConfirmation

**Comment by Severnity** [comment]
@DitriXNew если склад в документе находится в табличной части и используется несколько складов, то поле склад в списке документов пустое
