### ISSUE TITLE
Базовая роль доступа

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#8]
Необходимо создать роль доступа (Default role) которая позволит пользователю зайти в IRP, но при этом он ничего увидеть не должен

Это нужно для настройки прав доступа

**Comment by DitriXNew** [comment]
@Severnity  Напомни плиз, какой смысл этой роли?
Ну т.е. почему типо не назначить просто из нескольких ролей это все?

**Comment by Severnity** [comment]
когда назначаю роли с помощью системы прав доступа у меня при входе в программу возникает ошибка 
![изображение](https://user-images.githubusercontent.com/66120736/85867681-e9654f00-b7d1-11ea-85f6-86f24fb4eef6.png)
Поэтому говорили о том, что нужна роль, которая дает только ограниченный доступ

**Comment by DitriXNew** [comment]
Была такая роль как Basic Role, вот теперь достаточно выбрать ее и выбрать роль типа запускаемого клиента, и все тогда будет работать
