### ISSUE TITLE
Sorting of ItemKeys

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#81]
![image](https://user-images.githubusercontent.com/32883592/86296883-8e34c180-bc02-11ea-8751-5d19d7a4f98e.png)

Язык интерфейса и данных турецкий.

**Comment by DitriXNew** [comment]
Задача не решабельна в принципе.
Для динамических списков - нет понятия представления полей, вообще.
И когда идет сортировка по ссылке, то 1С берет порядок полей представления и сортирует по ним, т.е. когда создаете процедуру, где в массив добавляются поля, по которым потом идет представление, то типо 1с должна формировать по этим полям, в порядке их добавления.
А так ключи товара строятся по сложным алгоритмам - получается что в динамическом списке нам никаким макаром не вывести сортировку по ним.

Но все куда хуже, так как сортировка по обычным полям тоже нифига не работает нормально, так как 1С нифига не строит сортировку по полям выборки в порядке добавления. Она вообще строит только по ей неведомой логике.
Так что любая сортировка ссылочным типов во всей конфигурации, на текущий момент, никак не может быть решена.

**Comment by bryaleks** [comment]
Если задача не решабельна из за того что платформа не поддерживает какие то механизмы сортировка, значит нужно подумать об отключении сортировки по ссылочным полям в формах. Лучше пусть пользователь не сможет отсортировать чем дать ему возможность отсортировать не правильно.
И для ItemKey думаю стоит подумать над тем что бы представление все таки формировать не "на лету", а реализовать наименовение (до тех пор пока платформа не позволит сделать иначе)

**Comment by bryaleks** [comment]
@DitriXNew замолчать данную проблему не получится.

**Comment by Severnity** [comment]
сделать наименования у айтем ки
сделать механизм который будет проверять изменение доп реквизитов которые являются составляющими айтем ки и перезаполнять наименования

**Comment by DitriXNew** [comment]
Сделал обновление наименований при записи и по нажатии кнопки, регламенты потом отдельно придумаем
