### ISSUE TITLE
 SI/R4012B_StockReservation (Expense)

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#818]
должен стоять отбор UseSC, так как с резерва снимается то, что физически отгрузилось (на то на что есть SC, либо же то что SI отгружает сам)

**Comment by bryaleks** [comment]
проверить актуальность

**Comment by bryaleks** [comment]
тройка документов SO/SC/SI

SO - если ставит в резерв, снимает с фристока ложит на сток резерешн
SC - если на основании SO или SI снимает остаток с сток резервешна
SI - если делает отгрузку сам и на основании SO снимает с сток резервешна, если не делает отгрузку то в зависимости от остатка по SO может добавлять сток резервешн

**Comment by Severnity** [comment]
@bryaleks есть SI не на основании SO (первый в цепочке).
![image](https://user-images.githubusercontent.com/66120736/108041102-c92b1e80-7046-11eb-9144-96ff9565601c.png)
как и понимаю в Stock reservation  ещё одной строки по движениям не хватает
![image](https://user-images.githubusercontent.com/66120736/108041333-098a9c80-7047-11eb-9b9c-a00f6c4c326f.png)

**Comment by Severnity** [comment]
по сути задача
