### ISSUE TITLE
New register movement fix

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#829]

**Comment by bryaleks** [comment]
![image](https://user-images.githubusercontent.com/32883592/107795805-32224600-6d6a-11eb-8a1f-aaa7cda8c0a6.png)

**Comment by DitriXNew** [comment]
пофиксили кейс, когда две строки с одним ItemKey делаю не правильные движения по 4011

**Comment by DitriXNew** [comment]
исправили ошибки по  SO, SI, SC
Register  "R4012 Stock Reservation"

Теперь SI если не на SO то сам делает приход для SC в 4012 и добавили условия

Expense

		|WHERE
		|	NOT ItemListGroup.UseShipmentConfirmation
		|	OR ItemListGroup.ShipmentConfirmationExists
		|

Receipt
		|WHERE
		|	ItemListGroup.UseShipmentConfirmation
		|	AND NOT ItemListGroup.ShipmentConfirmationExists

Receipt
		|WHERE
		|	NOT ItemList.IsService
		|	AND NOT ItemList.SalesOrderExists
		|	AND ItemList.UseShipmentConfirmation

**Comment by bryaleks** [comment]
После тестов закрываем
