### ISSUE TITLE
Fix movements

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#844]
- [x] цепочка документов SO-SC-SI (в SI установлено use SC)
    SI не должен делать движения по регистру R4011 Free stocks
    SI не должен делать движения по регистру R4012 Stock Reservation
040138 check Sales invoice movements by the Register "R4011 Free stocks" SO-SC-SI (use SC)
040139 check Sales invoice movements by the Register "R4012 Stock Reservation" SO-SC-SI (use SC)

**Comment by DitriXNew** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vTzJIc8YPGy_KDMLMRz65DKWWk6rdTmfFVQJHMd08xinm0uw3Z1EQpsZVbql3GX10i-FSFtb973w17n/pubhtml?gid=1199399009&single=true
