### ISSUE TITLE
Attributes from extension

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#847]
Нужно добавить возможность чтобы в расширении можно было указывать какие реквизиты выводить и куда их подключать.

Иначе при подключении расширения возникает проблема в том, что постоянно приходится через настройки реквизиты выводить + надо лезть в конфигуратор чтобы понять какие реквизиты в расширении есть.

**Comment by DitriXNew** [comment]
Тут имеется ввиду некий программный апи, к которому будет обращаться ядро при старте и понимать - какие надо создать доп реквизиты
