### ISSUE TITLE
Unit calculation differences between GR/PI

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#875]
Кейс: есть номенклатура Х, учетная единица шт, дополнительная ед.изм. кг и тонна.
Поставщик работает в кг. Цены тоже в тоннах. Но в зависимости от партии, 1 шт может быть ровно 1 кг, а иногда 1,02 кг, а иногда 0.98 кг. Таким образом заказывая 1 тонну и рассчитывая получить 1000 штук, мы получаем 1005 или 995 шт, но они весят 1 тонну.
Итог:
PO = 1.000 кг (в проводках 1000 шт), цена в установке цен была введена в тоннах
GR = 1005 шт (в проводках 1005 шт)
PI = 1 тонна (в проводках 1000 шт)

Разницу по R1011B_PurchaseOrdersReceipt и (если будет) по R1012B_PurchaseOrdersInvoiceClosing закроет SOC
Но разницу по R1031B_ReceiptInvoicing и расхождение R4010B_ActualStocks, R4050B_StockInventory, R4031B_GoodsInTransitIncoming надо что бы закрывались чем то.

После поверхностного анализа пришли к тому, что это должны быть документы списания и оприходования.
Вводятся они на основании PI или SI (надо делать зеркальность, хотя со стороны AR это скорей всего будет не востребовано), так как затрагивают финансовый учет товаров.

**Comment by DitriXNew** [comment]
Сделали через редактирование QuantityInBaseUnit
