### ISSUE TITLE
Offers in the Sales return/Sales return order

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#902]
При выборе в Sales return Sales invoice, в случае если в SI была скидка, в Sales return не заполняется, при вводе суммы скидки вручную, общая суммы в табличной части Sales return не перерасчитываются.
![image](https://user-images.githubusercontent.com/66120736/110905741-a02f3e00-8313-11eb-8b55-fff2dffe03a6.png)

**Comment by DitriXNew** [comment]
@Severnity добавил скидки в документы. Надо обновить тесты
- [ ] PurchaseReturn
- [ ] PurchaseReturnOrder
- [ ] RetailReturnReceipt
- [ ] SalesReturn
- [ ] SalesReturnOrder
