### ISSUE TITLE
Lock data

### ISSUE THREAD

**Issue by DitriXNew** [IRPTeam/IRP#930]
Предусмотреть кейсы:
1. Запрет изменения по пользователю
2. Запрет изменения по дате от текущей

Пофиксить общие реквизиты
Добавить отбор по группам доступа

**Comment by DitriXEDT** [comment]
@DitriXNew я хочу взять эту задачу

**Comment by DitriXNew** [comment]
Ok

**Comment by DitriXNew** [comment]
@seramiti добавил возможность выполнения произвольного кода при выполнение периодических вещей.
Например, если надо блок делать по дате, то ставим галку что выполняем как код, и пишем код CurrentSessionDate(), и ставим условие.
Если надо по пользователю, то пишем путь к параметру сеанса и т.д.
Это позволяет ставить более гибкие настройки.

**Comment by DitriXNew** [comment]
Добавил отбор по группам доступа, если группа доступа не указан в блокировке, то действует на всех
Можно делать как @bryaleks делал, он просто создал пустые группы доступа, без профилей, и просто на них тягал разные условия, и указывал в них - на каких пользователей эта группа работает

**Comment by Severnity** [comment]
@DitriXNew как узнать путь параметра сеанса пользователя?

**Comment by DitriXNew** [comment]
> @DitriXNew как узнать путь параметра сеанса пользователя?

Просто писать SessionParameters.CurrentUser
Где CurrentUser - это и есть имя параметра сеанса
