### ISSUE TITLE
PackageUnit in Item

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#939]
Добавить реквизит PackageUnit (ед. хранения мест) в номенклатуру.
Назначение - в случае, если при отгрузке номенклатуры она отгружается определеннымой единицой измерения, ее можно тут указывать и подтягивать в печатные формы, а так же напоминать менеждеру набивающему заказ, что количество в документе (в ед. хранения) должно быть кратно коеффициенту единицы хранения места.

В данном реквизите должны выбираться доп. единицы измерения номенклатуры где колво больше 1

**Comment by DitriXNew** [comment]
Добавил в `SI `реквизиты:

`QuantityInPackageUnit `- количество в местах хранения, при этом единица мест хранения должна быть всегда основана только на базовой единице измерения. Если она не заполнена, то будет равна 1.

Я вклинился в функцию `CalculateQuantityInBaseUnit`, и там поставил условие на проверку наличия этого реквизита.

`PackageUnit `- единица хранения

**Comment by Severnity** [comment]
@DitriXNew если PackageUnit в номенклатуре не заполнена, то в документе она из основной единицы не заполняется
![image](https://user-images.githubusercontent.com/66120736/117764675-8fc51200-b235-11eb-8a89-92120e08acd9.png)
PackageUnit  будет только в Item или в Item key тоже?
Не совсем понимаю логику Unit при добавлении PackageUnit. Unit - это получается базовая единица хранения, а PackageUnit это единица хранения в упаковках? Также не поняла как правильно должен отрабатывать в документе пересчет цен при изменении Unit и PackageUnit

**Comment by bryaleks** [comment]
PackageUnit - это скорее ед измерения места, складской учет в разрезе этой ед. изм. не ведется.

По идее если в номенклатуре PackageUnit не заполнен, то в документе в поле PackageUnit должен заполняться сам Unit?@DitriXNew
