### ISSUE TITLE
Outgoing payment order and  Incoming payment order movements

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#952]
Необходимо прописать движения по новым регистрам для документов Outgoing payment order и Incoming payment order

**Comment by bryaleks** [comment]
R3033B_CashPlanningIncoming Приход
R3034B_CashPlanningOutgoing Приход

++R1022B_VendorsPaymentPlanning
Приход по PO, если указана предоплата и по PI если указана оплата с отсрочкой
Расход OPO, если в нем указан документ основания.
Company
BasisDocument
LegalName
Partner
Agreement

Amount

++R2022B_CustomersPaymentPlanning
Приход по SO, если указана предоплата и по SI если указана оплата с отсрочкой
Расход IPO, если в нем указан документ основания.

Company
BasisDocument
LegalName
Partner
Agreement

Amount

**Comment by Severnity** [comment]
@bryaleks планирование перемещения и конвертации ДС тоже через эти регистры будет проходить?
