### ISSUE TITLE
Payment sheduling

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#953]
Необходим отчет по платежному календарю

**Comment by bryaleks** [comment]
Необходимо реализовать простой механизм планирования расхода и прихода ДС.

Документы планирования:
- IPO (Incomming payment order) - определяет ожидаемых приход ДС
- OPO (Outgoing payment order) - определяет ожидаемый расход ДС

IPO/OPO могут быть созданы как независимо, так и на основании других документов. Основанием будут являться SO/SI/PO/PI.

Учет времени планирование необходимо вести как в разрезе дат, так и в разрезе периодов планирования. Например, оплата каждую среду четной недели года - период планирования 2 недели, дата оплаты ХХ число.

Сценарий 1:
1. Создан PO от 01.05.2021 на сумму 10.000. Условия оплаты: 30% предоплата + 70% с 15 дневной отсрочкой.
2. Создан OPO-1 на сумму 3.000, в котором указан PO, период планирования "период 1" и дата оплаты 05.05.2021
3. Проведена оплата по банку BP от 05.05.2021, в которой указан OPO-1
4. На основании PO введен PI от 10.05.2021 на сумма 10.000, в Payments у него указано 7.000 и дата оплаты 25.05.2021
5. Создан OPO-2 на сумму 7.000, в котором указан PI, период планирования "период 2" и дата оплаты 25.05.2021
6. Проведена оплата наличными CP от 26.05.2021 на сумма 7.000, в которой указан OPO-2

Отчеты:
1. Payment planning of vendors document - Отчет, который покажет какие документы основания необходимо распланировать. При первой итерации, в этот отчет попадают PO в которых есть предоплата и PI в которых есть оплата с отсрочкой. Аналитика: Company, BasisDocument, PaymentTerms, CashMovementType, PlaningDocument // AmountBasis, AmountPlanned, AmountToBePlanned.
2. Planned payments to vendors - Отчет который покажет план-фактный анализ оплат поставщикам. Документы планирования приход, документы оплаты расход. Аналитика: Company, BasisDocument, Partner, LegalName, PaymentTerms, CashMovementType, PlaningDocument // AmountPlanned, AmountPayed, AmountToBePayed (общая сумма запланированных оплат), DuePayments (оплаты срок которых еще не наступил), OverdurePayments (просроченные оплаты).
3. Payment calendar - плоская таблица по дням в колонках, где будет показываться цифры в разрезе некой аналитики в строках (организация, касса/банк, статья ддс, контрагент, док основания и т.д.).
- Кассовый разрыв - на основании данных планирования расхода и прохода ДС, а так же текущего остатка, должна быть возможность сформировать прогноз по предполагаемым остаткам будущих периодов.
