### ISSUE TITLE
Services should be filtered in stock documents

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#978]
В табличной части товаров, нужно поставить фильтр на выбор услуг.
Bundling
GoodsReceipt
InternalSupplyRequest
InventoryTransfer
InventoryTransferOrder
ItemStockAdjustment
PhysicalCountByLocation
PhysicalInventory
PlannedReceiptReservation
ShipmentConfirmation
StockAdjustmentAsSurplus
StockAdjustmentAsWriteOff
Unbundling

**Comment by Severnity** [comment]
характерно для любого другого языка кроме английского
