### ISSUE TITLE
Doubled field in ItemKey

### ISSUE THREAD

**Issue by bryaleks** [IRPTeam/IRP#979]
![image](https://user-images.githubusercontent.com/32883592/124512768-dcfed380-dde1-11eb-863c-c38ce9f2a018.png)

**Comment by Severnity** [comment]
@bryaleks у меня в этой форме только одна колонка item key
![image](https://user-images.githubusercontent.com/66120736/124722277-92c93f80-df12-11eb-8688-e51f23563339.png)

**Comment by bryaleks** [comment]
Я удалил все расширения, почистил кеш все равно выходит двойной итем кей.
Но что интересно у новосозданного пользователя такой проблемы нет. так как это видимо частный случай базы задачку закрываю
