### ISSUE TITLE
New registers movements

### ISSUE THREAD

**Issue by Severnity** [IRPTeam/IRP#988]
Необходимо добавить движения по новым регистрам

- [x] PI - R5022T_Expenses (в случае если услуги, должна падать Net amount)

- [x] SI - R5021T_Revenues

- [x] Cash revenue -R5021T_Revenues

- [x] Cash expense - R5022T_Expenses

- [x] Retail sales receipt - R5021T_Revenues, R2001 Sales

- [x] Retail return receipt - R2002T_SalesReturns,  R5021T_Revenues (сторнирование)

- [x] Sales return - R5021T_Revenues (сторнирование)

- [x] Purchase return - R5022T_Expenses (сторнирование)

**Comment by bryaleks** [comment]
Надо переименовать регистры и добавить проводки в 3050/2050 по новой логике
1. Retail cash - R3050_RetailCash
2. Retail sales - R2050_RetailSales
3. T10000B_RowIDMovements = T1010B_RowIDMovements
4. T10000T_RowIDMovements = T1010T_RowIDMovements
